brew tap homebrew/cask-drivers
brew install --cask discord
brew install --cask iterm2
brew install --cask karabiner-elements
brew install --cask logitech-options
brew install --cask mactex-no-gui
brew install --cask mactracker
brew install --cask microsoft-teams
brew install --cask multipass
brew install --cask plex
brew install --cask postman
brew install --cask skim
brew install --cask spotify
brew install --cask teamviewer
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask vnc-viewer
brew install --cask xquartz
brew install --cask kitty
