return {
    kind = {
        Text = '',
        Method = '',
        Function = '',
        Constructor = '',
        Field = 'ﰠ',
        Variable = '',
        Class = 'ﴯ',
        Interface = '',
        Module = '',
        Property = 'ﰠ',
        Unit = '塞',
        Value = '',
        Enum = '',
        Keyword = '',
        Snippet = '',
        Color = '',
        File = '',
        Reference = '',
        Folder = '',
        EnumMember = '',
        Constant = '',
        Struct = 'פּ',
        Event = '',
        Operator = '',
        TypeParameter = '',
        Namespace = '',
        Package = '',
        String = '',
        Number = '',
        Boolean = '',
        Array = '',
        Object = '',
        Key = '',
        Null = 'ﳠ',
    },
    ui = {
        Comment = '',
        ChevronRight = '>',
        Table = '',
        Calendar = '',
    },
    misc = {
        Tag = '',
        Watch = '',
    },
}
