- name: Create ~/.config
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
  tags:
    - install
    - home
    - link

- name: Find files to symlink to home
  find:
    paths:
      - "{{ lookup('env', 'HOME') }}/dotfiles/home"
      - "{{ lookup('env', 'HOME') }}/dotfiles/git"
    recurse: no
    file_type: any
    hidden: yes
  register: home_config
  tags:
    - install
    - home
    - link

- name: Symlink files to home
  file:
    src: "{{item.path}}"
    dest: "~/{{item.path | basename}}"
    state: link
  loop: "{{ home_config.files }}"
  loop_control:
    label: "~/{{item.path | basename}}"
  tags:
    - install
    - home
    - link

- name: Symlink icon script
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/scripts/replace_icons.sh"
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/icons"
    state: link
  tags:
    - install
    - link
