- name: Check gh exists
  shell: which gh
  ignore_errors: yes
  register: gh_result
  failed_when: gh_result.rc != 1 and gh_result.rc != 0
  when: ansible_facts['os_family'] != "Debian"
  tags:
    - install

- name: Ensure gh cli is available in apt
  shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt update
  when: (ansible_facts['os_family'] == "Debian") and (gh_result.rc != 0)
  become: True
  tags:
    - install

- name: Install common packages
  vars: 
      should_be_root: "{{ False if ansible_pkg_mgr == 'homebrew' else True }}"
  ansible.builtin.package:
    name:
      - zsh
      - gcc
      - nodejs
      - ctags
      - tmux
      - ripgrep
      - gh
    state: present
  become: "{{ should_be_root }}"
  tags:
    - install

- name: Install cargo (linux)
  apt:
   name: [ "cargo" ]
  when: ansible_facts['os_family'] == "Debian"
  become: True
  tags:
    - install

- name: Install stylua
  shell: cargo install stylua
  tags:
    - install

- name: Install delta
  shell: cargo install git-delta
  tags:
    - install

- name: Install emojify
  shell: sh -c "curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o /usr/local/bin/emojify && chmod +x /usr/local/bin/emojify"
  become: True
  tags:
    - install
