- name: Install zsh
  ansible.builtin.package:
    name:
      - zsh
    state: present
  tags:
    - install
    - zsh

- name: Check if Oh-My-Zsh is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh

  tags:
    - install
    - zsh

- name: Install Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not oh_my_zsh.stat.exists
  tags:
    - install
    - zsh

- name: Setup propmt
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/zsh/prompt/spaceship.zsh"
    dest: /usr/local/share/zsh/site-functions/prompt_spaceship_setup
    state: link
  become: True
  tags:
    - install
    - zsh

- name: Install zsh-async
  shell: git submodule update --init
  tags:
    - install
    - zsh

- name: Install zsh-z
  ansible.builtin.git:
    repo: 'https://github.com/agkozak/zsh-z.git'
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-z"
  tags:
    - install
    - zsh

- name: Symlink zsh config
  file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/zsh"
    dest: "{{ lookup('env', 'HOME') }}/.config/zsh"
    state: link
  tags:
    - install
    - zsh
