local Color, c, Group, g, s = require("colorbuddy").setup()

vim.g.colors_name = 'colorscheme'

---------- COLORS ----------

Color.new('black', '#000000')
Color.new('bg1', '#1c1c1c')
Color.new('bg2', '#363944')
Color.new('fg1', '#eeeeee')
Color.new('error', '#ff0033')
Color.new('bg_red', '#ff6077')
Color.new('bg_green', '#a7df78')
Color.new('bg_blue', '#85d3f2')
Color.new('diff_red', '#55393d')
Color.new('diff_green', '#394634')
Color.new('diff_blue', '#354157')
Color.new('diff_yellow', '#4e432f')
Color.new('diff_orange', '#e5d5ac')
Color.new('red', '#fc5d7c')
Color.new('orange', '#d78700')
Color.new('yellow', '#e7c664')
Color.new('green', '#9ed072')
Color.new('blue', '#76cce0')
Color.new('purple', '#b39df3')
Color.new('grey', '#7f8490')

---------- TERM COLORS ----------

vim.g.terminal_color_0  = '#1d1f21'
vim.g.terminal_color_1  = '#ff2200'
vim.g.terminal_color_2  = '#198844'
vim.g.terminal_color_3  = '#bbbb00'
vim.g.terminal_color_4  = '#00bbbb'
vim.g.terminal_color_5  = '#bb00bb'
vim.g.terminal_color_6  = '#00bbbb'
vim.g.terminal_color_7  = '#f5f5f5'
vim.g.terminal_color_8  = '#989698'
vim.g.terminal_color_9  = '#ff2200'
vim.g.terminal_color_10 = '#198844'
vim.g.terminal_color_11 = '#d8865f'
vim.g.terminal_color_12 = '#00bbbb'
vim.g.terminal_color_13 = '#bb00bb'
vim.g.terminal_color_14 = '#00bbbb'
vim.g.terminal_color_15 = '#ffffff'


---------- GROUPS ----------

Group.new('Normal', c.fg1, c.bg1)
Group.new('Terminal', c.fg1, c.bg1)
Group.new('EndOfBuffer', c.bg1, c.bg1)
Group.new('Folded', c.grey, c.bg1)
Group.new('ToolbarLine', c.fg1, c.bg2)
Group.new('SignColumn', c.fg1, c.none)
Group.new('FoldColumn', c.grey, c.none)
Group.new('IncSearch', c.bg1, c.bg_red)
Group.new('Search', c.bg1, c.bg_green)
Group.new('ColorColumn', c.none, c.bg1)
Group.new('Conceal', c.grey, c.none)
Group.new('Cursor', c.none, c.none, s.reverse)

Group.new('vCursor', g.Cursor, g.Cursor, g.Cursor)
Group.new('iCursor', g.Cursor, g.Cursor, g.Cursor)
Group.new('lCursor', g.Cursor, g.Cursor, g.Cursor)
Group.new('CursorIM', g.Cursor, g.Cursor, g.Cursor)

Group.new('CursorLine', c.red, c.bg1)
Group.new('CursorColumn', c.none, c.bg1)
Group.new('LineNr', c.grey, c.none)
Group.new('CursorLineNr', c.fg1, c.none)

Group.new('DiffAdd', c.none, c.diff_green)
Group.new('DiffChange', c.none, c.diff_blue)
Group.new('DiffDelete', c.none, c.diff_red)
Group.new('DiffText', c.bg1, c.diff_orange)
Group.new('Directory', c.green, c.none)
Group.new('ErrorMsg', c.red, c.none)
Group.new('WarningMsg', c.yellow, c.none, s.bold)
Group.new('ModeMsg', c.fg1, c.none, s.bold)
Group.new('MoreMsg', c.blue, c.none, s.bold)
Group.new('MatchParen', c.none, c.bg2)
Group.new('NonText', c.bg2, c.none)
Group.new('Whitespace', c.bg2, c.none)
Group.new('SpecialKey', c.bg2, c.none)
Group.new('Pmenu', c.fg1, c.bg2)
Group.new('PmenuSbar', c.none, c.bg2)
Group.new('PmenuSel', c.bg1, c.bg_green)
Group.new('WildMenu', g.PmenuSel, g.PmenuSel, g.PmenuSel)

Group.new('PmenuThumb', c.none, c.grey)
Group.new('NormalFloat', c.fg1, c.bg2)
Group.new('Question', c.yellow, c.none)
Group.new('SpellBad', c.red, c.none, s.undercurl, c.red)
Group.new('SpellCap', c.yellow, c.none, s.undercurl, c.yellow)
Group.new('SpellLocal', c.blue, c.none, s.undercurl, c.blue)
Group.new('SpellRare', c.purple, c.none, s.undercurl, c.purple)
Group.new('StatusLine', c.fg1, c.none)
Group.new('StatusLineTerm', c.fg1, c.bg2)
Group.new('StatusLineNC', c.grey, c.bg1)
Group.new('StatusLineTermNC', c.grey, c.bg1)
Group.new('TabLine', c.none, c.yellow)
Group.new('TabLineFill', c.grey, c.bg1)
Group.new('TabLineSel', c.none, c.bg_red)
Group.new('VertSplit', c.grey, c.none)
Group.new('Visual', c.none, c.bg2)
Group.new('VisualNOS', c.none, c.bg2, s.underline)
Group.new('QuickFixLine', c.blue, c.none, s.bold)
Group.new('Debug', c.yellow, c.none)
Group.new('debugPC', c.bg1, c.green)
Group.new('debugBreakpoint', c.bg1, c.red)
Group.new('ToolbarButton', c.bg1, c.bg_blue)

Group.new('ErrorText', c.error, c.none, s.undercurl, c.red)
Group.new('WarningText', c.none, c.none, s.undercurl, c.yellow)
Group.new('InfoText', c.none, c.none, s.undercurl, c.blue)
Group.new('HintText', c.none, c.diff_green, s.undercurl, c.green)
Group.new('ErrorFloat', c.red, c.bg2)
Group.new('WarningFloat', c.yellow, c.bg2)
Group.new('InfoFloat', c.blue, c.bg2)
Group.new('HintFloat', c.green, c.bg2)
Group.new('RedSign', c.red, c.bg1)
Group.new('OrangeSign', c.orange, c.bg1)
Group.new('YellowSign', c.yellow, c.bg1)
Group.new('GreenSign', c.green, c.bg1)
Group.new('BlueSign', c.blue, c.bg1)
Group.new('PurpleSign', c.purple, c.bg1)

Group.new('CurrentWord', c.bg1, c.green)

Group.new('Substitute', c.bg1, c.yellow)
Group.new('LspDiagnosticsFloatingError', g.ErrorFloat, g.ErrorFloat, g.ErrorFloat)
Group.new('LspDiagnosticsFloatingWarning', g.WarningFloat, g.WarningFloat, g.WarningFloat)
Group.new('LspDiagnosticsFloatingInformation', g.InfoFloat, g.InfoFloat, g.InfoFloat)
Group.new('LspDiagnosticsFloatingHint', g.HintFloat, g.HintFloat, g.HintFloat)
Group.new('LspDiagnosticsDefaultError', g.ErrorText, g.ErrorText, g.ErrorText)
Group.new('LspDiagnosticsDefaultWarning', g.WarningText, g.WarningText, g.WarningText)
Group.new('LspDiagnosticsDefaultInformation', g.InfoText, g.InfoText, g.InfoText)
Group.new('LspDiagnosticsDefaultHint', g.HintText, g.HintText, g.HintText)
Group.new('LspDiagnosticsVirtualTextError', c.red)
Group.new('LspDiagnosticsVirtualTextWarning', c.orange)
Group.new('LspDiagnosticsVirtualTextInformation', c.yellow)
Group.new('LspDiagnosticsVirtualTextHint', c.grey)
Group.new('LspDiagnosticsUnderlineError', g.ErrorText, g.ErrorText, g.ErrorText)
Group.new('LspDiagnosticsUnderlineWarning', g.WarningText, g.WarningText, g.WarningText)
Group.new('LspDiagnosticsUnderlineInformation', g.InfoText, g.InfoText, g.InfoText)
Group.new('LspDiagnosticsUnderlineHint', g.HintText, g.HintText, g.HintText)
Group.new('LspDiagnosticsSignError', g.RedSign, g.RedSign, g.RedSign)
Group.new('LspDiagnosticsSignWarning', g.OrangeSign, g.OrangeSign, g.OrangeSign)
Group.new('LspDiagnosticsSignInformation', g.BlueSign, g.BlueSign, g.BlueSign)
Group.new('LspDiagnosticsSignHint', g.YellowSign, g.YellowSign, g.YellowSign)
Group.new('LspReferenceText', g.CurrentWord, g.CurrentWord, g.CurrentWord)
Group.new('LspReferenceRead', g.CurrentWord, g.CurrentWord, g.CurrentWord)
Group.new('LspReferenceWrite', g.CurrentWord, g.CurrentWord, g.CurrentWord)
Group.new('TermCursor', g.Cursor, g.Cursor, g.Cursor)
Group.new('healthError', c.red)
Group.new('healthSuccess', c.green)
Group.new('healthWarning', c.yellow)

Group.new('Type', c.blue, c.none)
Group.new('Structure', c.blue, c.none)
Group.new('StorageClass', c.blue, c.none)
Group.new('Identifier', c.orange, c.none)
Group.new('Constant', c.orange, c.none)

Group.new('PreProc', c.red, c.none)
Group.new('PreCondit', c.red, c.none)
Group.new('Include', c.red, c.none)
Group.new('Keyword', c.red, c.none)
Group.new('Define', c.red, c.none)
Group.new('Typedef', c.red, c.none)
Group.new('Exception', c.red, c.none)
Group.new('Conditional', c.red, c.none)
Group.new('Repeat', c.red, c.none)
Group.new('Statement', c.red, c.none)
Group.new('Macro', c.purple, c.none)
Group.new('Error', c.red, c.none)
Group.new('Label', c.purple, c.none)
Group.new('Special', c.purple, c.none)
Group.new('SpecialChar', c.purple, c.none)
Group.new('Boolean', c.purple, c.none)
Group.new('String', c.yellow, c.none)
Group.new('Character', c.yellow, c.none)
Group.new('Number', c.purple, c.none)
Group.new('Float', c.purple, c.none)
Group.new('Function', c.green, c.none)
Group.new('Operator', c.red, c.none)
Group.new('Title', c.red, c.none, s.bold)
Group.new('Tag', c.orange, c.none)
Group.new('Delimiter', c.fg1, c.none)

Group.new('Comment', c.grey, c.none, s.italic)
Group.new('SpecialComment', c.grey, c.none, s.italic)
Group.new('Todo', c.blue, c.none, s.italic)

Group.new('Ignore', c.grey, c.none)
Group.new('Underlined', c.none, c.none, s.underline)

Group.new('Fg', c.fg1, c.none)
Group.new('Grey', c.grey, c.none)
Group.new('Red', c.red, c.none)
Group.new('Orange', c.orange, c.none)
Group.new('Yellow', c.yellow, c.none)
Group.new('Green', c.green, c.none)
Group.new('Blue', c.blue, c.none)
Group.new('Purple', c.purple, c.none)

Group.new('RedItalic', c.red, c.none)
Group.new('OrangeItalic', c.orange, c.none)
Group.new('YellowItalic', c.yellow, c.none)
Group.new('GreenItalic', c.green, c.none)
Group.new('BlueItalic', c.blue, c.none)
Group.new('PurpleItalic', c.purple, c.none)

Group.new('ErrorLine', c.none, c.none)
Group.new('WarningLine', c.none, c.none)
Group.new('InfoLine', c.none, c.none)
Group.new('HintLine', c.none, c.none)

Group.new('markdownH1', c.red, c.none, s.bold)
Group.new('markdownH2', c.orange, c.none, s.bold)
Group.new('markdownH3', c.yellow, c.none, s.bold)
Group.new('markdownH4', c.green, c.none, s.bold)
Group.new('markdownH5', c.blue, c.none, s.bold)
Group.new('markdownH6', c.purple, c.none, s.bold)
Group.new('markdownUrl', c.blue, c.none, s.underline)
Group.new('markdownItalic', c.none, c.none, s.italic)
Group.new('markdownBold', c.none, c.none, s.bold)
Group.new('markdownItalicDelimiter', c.grey, c.none, s.italic)
Group.new('markdownCode', c.green)
Group.new('markdownCodeBlock', c.green)
Group.new('markdownCodeDelimiter', c.green)
Group.new('markdownBlockquote', c.grey)
Group.new('markdownListMarker', c.red)
Group.new('markdownOrderedListMarker', c.red)
Group.new('markdownRule', c.purple)
Group.new('markdownHeadingRule', c.grey)
Group.new('markdownUrlDelimiter', c.grey)
Group.new('markdownLinkDelimiter', c.grey)
Group.new('markdownLinkTextDelimiter', c.grey)
Group.new('markdownHeadingDelimiter', c.grey)
Group.new('markdownLinkText', c.red)
Group.new('markdownUrlTitleDelimiter', c.green)
Group.new('markdownIdDeclaration', g.markdownLinkText, g.markdownLinkText, g.markdownLinkText)
Group.new('markdownBoldDelimiter', c.grey)
Group.new('markdownId', c.yellow)
Group.new('mkdURL', c.blue, c.none, s.underline)
Group.new('mkdInlineURL', c.blue, c.none, s.underline)
Group.new('mkdItalic', c.grey, c.none, s.italic)
Group.new('mkdCodeDelimiter', c.green)
Group.new('mkdBold', c.grey)
Group.new('mkdLink', c.red)
Group.new('mkdHeading', c.grey)
Group.new('mkdListItem', c.red)
Group.new('mkdRule', c.purple)
Group.new('mkdDelimiter', c.grey)
Group.new('mkdId', c.yellow)

Group.new('TSAnnotation', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSAttribute', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSBoolean', c.purple)
Group.new('TSCharacter', c.yellow)
Group.new('TSComment', c.grey)
Group.new('TSConditional', c.red)
Group.new('TSConstBuiltin', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('TSConstMacro', c.orange)
Group.new('TSConstant', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('TSConstructor', g.Fg, g.Fg, g.Fg)
Group.new('TSCustomType', c.purple)
Group.new('TSError', g.Normal, g.Normal, g.Normal)
Group.new('TSException', c.red)
Group.new('TSField', c.green)
Group.new('TSFloat', c.purple)
Group.new('TSFuncBuiltin', c.green)
Group.new('TSFuncMacro', c.green)
Group.new('TSFunction', c.green)
Group.new('TSInclude', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSKeyword', c.red)
Group.new('TSKeywordFunction', c.red)
Group.new('TSLabel', c.red)
Group.new('TSMethod', c.green)
Group.new('TSNamespace', c.purple)
Group.new('TSNumber', c.purple)
Group.new('TSOperator', c.red)
Group.new('TSParameter', c.none, c.none)
Group.new('TSParameterReference', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('TSProperty', c.none, c.none)
Group.new('tsxTSProperty', c.green)
Group.new('TSPunctBracket', g.Fg, g.Fg, g.Fg)
Group.new('TSPunctDelimiter', c.grey)
Group.new('TSPunctSpecial', g.Fg, g.Fg, g.Fg)
Group.new('TSRepeat', c.red)
Group.new('TSString', c.yellow)
Group.new('TSStringEscape', c.green)
Group.new('TSStringRegex', c.green)
Group.new('TSStructure', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSTag', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSTagDelimiter', c.red)
Group.new('TSText', c.green)
Group.new('TSEmphasis', c.none, c.none, s.bold)
-- Group.new('TSUnderline', c.none, c.none, s.underline)
Group.new('TSType', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSTypeBuiltin', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('TSURI', g.markdownUrl, g.markdownUrl, g.markdownUrl)
Group.new('TSVariable', g.Fg, g.Fg, g.Fg)
Group.new('TSVariableBuiltin', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)

-- Group.new('CocHoverRange', c.none, c.none, s.bold + s.underline)
Group.new('CocErrorFloat', g.ErrorFloat, g.ErrorFloat, g.ErrorFloat)
Group.new('CocWarningFloat', g.WarningFloat, g.WarningFloat, g.WarningFloat)
Group.new('CocInfoFloat', g.InfoFloat, g.InfoFloat, g.InfoFloat)
Group.new('CocHintFloat', g.HintFloat, g.HintFloat, g.HintFloat)
Group.new('CocErrorHighlight', g.ErrorText, g.ErrorText, g.ErrorText)
Group.new('CocWarningHighlight', g.WarningText, g.WarningText, g.WarningText)
Group.new('CocInfoHighlight', g.InfoText, g.InfoText, g.InfoText)
Group.new('CocHintHighlight', g.HintText, g.HintText, g.HintText)
Group.new('CocHighlightText', g.CurrentWord, g.CurrentWord, g.CurrentWord)
Group.new('CocErrorSign', g.RedSign, g.RedSign, g.RedSign)
Group.new('CocWarningSign', g.OrangeSign, g.OrangeSign, g.OrangeSign)
Group.new('CocInfoSign', g.BlueSign, g.BlueSign, g.BlueSign)
Group.new('CocHintSign', g.YellowSign, g.YellowSign, g.YellowSign)
Group.new('CocWarningVirtualText', c.grey)
Group.new('CocErrorVirtualText', c.grey)
Group.new('CocInfoVirtualText', c.grey)
Group.new('CocHintVirtualText', c.grey)
Group.new('CocErrorLine', g.ErrorLine, g.ErrorLine, g.ErrorLine)
Group.new('CocWarningLine', g.WarningLine, g.WarningLine, g.WarningLine)
Group.new('CocInfoLine', g.InfoLine, g.InfoLine, g.InfoLine)
Group.new('CocHintLine', g.HintLine, g.HintLine, g.HintLine)
Group.new('CocCodeLens', c.grey)
Group.new('HighlightedyankRegion', g.Visual, g.Visual, g.Visual)
Group.new('CocGitAddedSign', g.GreenSign, g.GreenSign, g.GreenSign)
Group.new('CocGitChangeRemovedSign', g.PurpleSign, g.PurpleSign, g.PurpleSign)
Group.new('CocGitChangedSign', g.BlueSign, g.BlueSign, g.BlueSign)
Group.new('CocGitRemovedSign', g.RedSign, g.RedSign, g.RedSign)
Group.new('CocGitTopRemovedSign', g.RedSign, g.RedSign, g.RedSign)
Group.new('CocExplorerBufferRoot', c.red)
Group.new('CocExplorerBufferExpandIcon', c.blue)
Group.new('CocExplorerBufferBufnr', c.yellow)
Group.new('CocExplorerBufferModified', c.yellow)
Group.new('CocExplorerBufferReadonly', c.red)
Group.new('CocExplorerBufferBufname', c.grey)
Group.new('CocExplorerBufferFullpath', c.grey)
Group.new('CocExplorerFileRoot', c.red)
Group.new('CocExplorerFileRootName', c.green)
Group.new('CocExplorerFileExpandIcon', c.blue)
Group.new('CocExplorerFileFullpath', c.grey)
Group.new('CocExplorerFileDirectory', c.green)
Group.new('CocExplorerFileGitStaged', c.purple)
Group.new('CocExplorerFileGitUnstaged', c.yellow)
Group.new('CocExplorerFileGitRootStaged', c.purple)
Group.new('CocExplorerFileGitRootUnstaged', c.yellow)
Group.new('CocExplorerGitPathChange', g.Fg, g.Fg, g.Fg)
Group.new('CocExplorerGitContentChange', g.Fg, g.Fg, g.Fg)
Group.new('CocExplorerGitRenamed', c.purple)
Group.new('CocExplorerGitCopied', g.Fg, g.Fg, g.Fg)
Group.new('CocExplorerGitAdded', c.green)
Group.new('CocExplorerGitUntracked', c.blue)
Group.new('CocExplorerGitUnmodified', g.Fg, g.Fg, g.Fg)
Group.new('CocExplorerGitUnmerged', c.orange)
Group.new('CocExplorerGitMixed', g.Fg, g.Fg, g.Fg)
Group.new('CocExplorerGitModified', c.yellow)
Group.new('CocExplorerGitDeleted', c.red)
Group.new('CocExplorerGitIgnored', c.grey)
Group.new('CocExplorerFileSize', c.blue)
Group.new('CocExplorerTimeAccessed', c.purple)
Group.new('CocExplorerTimeCreated', c.purple)
Group.new('CocExplorerTimeModified', c.purple)
Group.new('CocExplorerFileRootName', c.orange)
Group.new('CocExplorerBufferNameVisible', c.green)
Group.new('CocExplorerIndentLine', g.Conceal, g.Conceal, g.Conceal)
Group.new('CocExplorerHelpDescription', c.grey)
Group.new('CocExplorerHelpHint', c.grey)

Group.new('GitGutterAdd', g.GreenSign, g.GreenSign, g.GreenSign)
Group.new('GitGutterChange', g.BlueSign, g.BlueSign, g.BlueSign)
Group.new('GitGutterDelete', g.RedSign, g.RedSign, g.RedSign)
Group.new('GitGutterChangeDelete', g.PurpleSign, g.PurpleSign, g.PurpleSign)

Group.new('SignifySignAdd', g.GreenSign, g.GreenSign, g.GreenSign)
Group.new('SignifySignChange', g.BlueSign, g.BlueSign, g.BlueSign)
Group.new('SignifySignDelete', g.RedSign, g.RedSign, g.RedSign)
Group.new('SignifySignChangeDelete', g.PurpleSign, g.PurpleSign, g.PurpleSign)

Group.new('EasyMotionTarget', g.Search, g.Search, g.Search)
Group.new('EasyMotionShade', c.grey)

Group.new('multiple_cursors_cursor', g.Cursor, g.Cursor, g.Cursor)
Group.new('multiple_cursors_visual', g.Visual, g.Visual, g.Visual)

Group.new('plug1', c.red, c.none, s.bold)
Group.new('plugNumber', c.yellow, c.none, s.bold)
Group.new('plug2', c.blue)
Group.new('plugBracket', c.blue)
Group.new('plugName', c.green)
Group.new('plugDash', c.red)
Group.new('plugNotLoaded', c.grey)
Group.new('plugH2', c.purple)
Group.new('plugMessage', c.purple)
Group.new('plugError', c.red)
Group.new('plugRelDate', c.grey)
Group.new('plugStar', c.purple)
Group.new('plugUpdate', c.blue)
Group.new('plugDeleted', c.grey)
Group.new('plugEdge', c.purple)

Group.new('texStatement', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('texOnlyMath', c.grey)
Group.new('texDefName', c.yellow)
Group.new('texNewCmd', c.orange)
Group.new('texCmdName', c.blue)
Group.new('texBeginEnd', c.red)
Group.new('texBeginEndName', c.green)
Group.new('texDocType', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('texDocTypeArgs', c.orange)
Group.new('texInputFile', c.green)
Group.new('texFileArg', c.green)
Group.new('texCmd', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('texCmdPackage', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('texCmdDef', c.red)
Group.new('texDefArgName', c.yellow)
Group.new('texCmdNewcmd', c.red)
Group.new('texCmdClass', c.red)
Group.new('texCmdTitle', c.red)
Group.new('texCmdAuthor', c.red)
Group.new('texCmdEnv', c.red)
Group.new('texCmdPart', c.red)
Group.new('texEnvArgName', c.green)

Group.new('htmlH1', c.red, c.none, s.bold)
Group.new('htmlH2', c.orange, c.none, s.bold)
Group.new('htmlH3', c.yellow, c.none, s.bold)
Group.new('htmlH4', c.green, c.none, s.bold)
Group.new('htmlH5', c.blue, c.none, s.bold)
Group.new('htmlH6', c.purple, c.none, s.bold)
Group.new('htmlLink', c.none, c.none, s.underline)
Group.new('htmlBold', c.none, c.none, s.bold)
Group.new('htmlBoldUnderline', c.none, c.none, s.bold + s.underline)
Group.new('htmlBoldItalic', c.none, c.none, s.bold + s.italic)
Group.new('htmlBoldUnderlineItalic', c.none, c.none, s.bold + s.underline + s.italic)
Group.new('htmlUnderline', c.none, c.none, s.underline)
Group.new('htmlUnderlineItalic', c.none, c.none, s.underline + s.italic)
Group.new('htmlItalic', c.none, c.none, s.italic)

Group.new('htmlTag', c.green)
Group.new('htmlEndTag', c.blue)
Group.new('htmlTagN', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('htmlTagName', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('htmlArg', c.blue)
Group.new('htmlScriptTag', c.purple)
Group.new('htmlSpecialTagName', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('htmlString', c.green)

Group.new('cssStringQ', c.green)
Group.new('cssStringQQ', c.green)
Group.new('cssAttrComma', c.grey)
Group.new('cssBraces', c.grey)
Group.new('cssTagName', c.purple)
Group.new('cssClassNameDot', c.grey)
Group.new('cssClassName', c.red)
Group.new('cssFunctionName', c.orange)
Group.new('cssAttr', c.green)
Group.new('cssCommonAttr', c.green)
Group.new('cssProp', c.blue)
Group.new('cssPseudoClassId', c.yellow)
Group.new('cssPseudoClassFn', c.green)
Group.new('cssPseudoClass', c.yellow)
Group.new('cssImportant', c.red)
Group.new('cssSelectorOp', c.orange)
Group.new('cssSelectorOp2', c.orange)
Group.new('cssColor', c.green)
Group.new('cssUnitDecorators', c.green)
Group.new('cssValueLength', c.green)
Group.new('cssValueInteger', c.green)
Group.new('cssValueNumber', c.green)
Group.new('cssValueAngle', c.green)
Group.new('cssValueTime', c.green)
Group.new('cssValueFrequency', c.green)
Group.new('cssVendor', c.grey)
Group.new('cssNoise', c.grey)

Group.new('lessMixinChar', c.grey)
Group.new('lessClass', c.red)
Group.new('lessFunction', c.orange)

Group.new('javaScriptNull', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('javaScriptIdentifier', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javaScriptParens', g.Fg, g.Fg, g.Fg)
Group.new('javaScriptBraces', g.Fg, g.Fg, g.Fg)
Group.new('javaScriptNumber', c.purple)
Group.new('javaScriptLabel', c.red)
Group.new('javaScriptGlobal', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javaScriptMessage', g.BlueItalic, g.BlueItalic, g.BlueItalic)

Group.new('jsNoise', g.Fg, g.Fg, g.Fg)
Group.new('Noise', g.Fg, g.Fg, g.Fg)
Group.new('jsParens', g.Fg, g.Fg, g.Fg)
Group.new('jsBrackets', g.Fg, g.Fg, g.Fg)
Group.new('jsObjectBraces', g.Fg, g.Fg, g.Fg)
Group.new('jsThis', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsUndefined', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('jsNull', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('jsNan', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('jsSuper', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('jsPrototype', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('jsFunction', c.red)
Group.new('jsGlobalNodeObjects', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsGlobalObjects', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsArrowFunction', c.red)
Group.new('jsArrowFuncArgs', g.Fg, g.Fg, g.Fg)
Group.new('jsFuncArgs', g.Fg, g.Fg, g.Fg)
Group.new('jsObjectProp', g.Fg, g.Fg, g.Fg)
Group.new('jsVariableDef', g.Fg, g.Fg, g.Fg)
Group.new('jsObjectKey', g.Fg, g.Fg, g.Fg)
Group.new('jsParen', g.Fg, g.Fg, g.Fg)
Group.new('jsParenIfElse', g.Fg, g.Fg, g.Fg)
Group.new('jsParenRepeat', g.Fg, g.Fg, g.Fg)
Group.new('jsParenSwitch', g.Fg, g.Fg, g.Fg)
Group.new('jsParenCatch', g.Fg, g.Fg, g.Fg)
Group.new('jsBracket', g.Fg, g.Fg, g.Fg)
Group.new('jsObjectValue', g.Fg, g.Fg, g.Fg)
Group.new('jsDestructuringBlock', g.Fg, g.Fg, g.Fg)
Group.new('jsBlockLabel', c.purple)
Group.new('jsFunctionKey', c.green)
Group.new('jsClassDefinition', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsDot', c.grey)
Group.new('jsSpreadExpression', c.purple)
Group.new('jsSpreadOperator', c.green)
Group.new('jsModuleKeyword', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsTemplateExpression', c.purple)
Group.new('jsTemplateBraces', c.purple)
Group.new('jsClassMethodType', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('jsExceptions', g.BlueItalic, g.BlueItalic, g.BlueItalic)

Group.new('javascriptOpSymbol', c.red)
Group.new('javascriptOpSymbols', c.red)
Group.new('javascriptIdentifierName', g.Fg, g.Fg, g.Fg)
Group.new('javascriptVariable', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javascriptObjectLabel', g.Fg, g.Fg, g.Fg)
Group.new('javascriptPropertyNameString', g.Fg, g.Fg, g.Fg)
Group.new('javascriptFuncArg', g.Fg, g.Fg, g.Fg)
Group.new('javascriptObjectLiteral', c.green)
Group.new('javascriptIdentifier', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('javascriptArrowFunc', c.red)
Group.new('javascriptTemplate', c.purple)
Group.new('javascriptTemplateSubstitution', c.purple)
Group.new('javascriptTemplateSB', c.purple)
Group.new('javascriptNodeGlobal', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javascriptDocTags', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('javascriptDocNotation', c.blue)
Group.new('javascriptClassSuper', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('javascriptClassName', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javascriptClassSuperName', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('javascriptOperator', c.red)
Group.new('javascriptBrackets', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBraces', g.Fg, g.Fg, g.Fg)
Group.new('javascriptLabel', c.purple)
Group.new('javascriptEndColons', c.grey)
Group.new('javascriptObjectLabelColon', c.grey)
Group.new('javascriptDotNotation', c.grey)
Group.new('javascriptGlobalArrayDot', c.grey)
Group.new('javascriptGlobalBigIntDot', c.grey)
Group.new('javascriptGlobalDateDot', c.grey)
Group.new('javascriptGlobalJSONDot', c.grey)
Group.new('javascriptGlobalMathDot', c.grey)
Group.new('javascriptGlobalNumberDot', c.grey)
Group.new('javascriptGlobalObjectDot', c.grey)
Group.new('javascriptGlobalPromiseDot', c.grey)
Group.new('javascriptGlobalRegExpDot', c.grey)
Group.new('javascriptGlobalStringDot', c.grey)
Group.new('javascriptGlobalSymbolDot', c.grey)
Group.new('javascriptGlobalURLDot', c.grey)
Group.new('javascriptMethod', c.green)
Group.new('javascriptMethodName', c.green)
Group.new('javascriptObjectMethodName', c.green)
Group.new('javascriptGlobalMethod', c.green)
Group.new('javascriptDOMStorageMethod', c.green)
Group.new('javascriptFileMethod', c.green)
Group.new('javascriptFileReaderMethod', c.green)
Group.new('javascriptFileListMethod', c.green)
Group.new('javascriptBlobMethod', c.green)
Group.new('javascriptURLStaticMethod', c.green)
Group.new('javascriptNumberStaticMethod', c.green)
Group.new('javascriptNumberMethod', c.green)
Group.new('javascriptDOMNodeMethod', c.green)
Group.new('javascriptES6BigIntStaticMethod', c.green)
Group.new('javascriptBOMWindowMethod', c.green)
Group.new('javascriptHeadersMethod', c.green)
Group.new('javascriptRequestMethod', c.green)
Group.new('javascriptResponseMethod', c.green)
Group.new('javascriptES6SetMethod', c.green)
Group.new('javascriptReflectMethod', c.green)
Group.new('javascriptPaymentMethod', c.green)
Group.new('javascriptPaymentResponseMethod', c.green)
Group.new('javascriptTypedArrayStaticMethod', c.green)
Group.new('javascriptGeolocationMethod', c.green)
Group.new('javascriptES6MapMethod', c.green)
Group.new('javascriptServiceWorkerMethod', c.green)
Group.new('javascriptCacheMethod', c.green)
Group.new('javascriptFunctionMethod', c.green)
Group.new('javascriptXHRMethod', c.green)
Group.new('javascriptBOMNavigatorMethod', c.green)
Group.new('javascriptServiceWorkerMethod', c.green)
Group.new('javascriptDOMEventTargetMethod', c.green)
Group.new('javascriptDOMEventMethod', c.green)
Group.new('javascriptIntlMethod', c.green)
Group.new('javascriptDOMDocMethod', c.green)
Group.new('javascriptStringStaticMethod', c.green)
Group.new('javascriptStringMethod', c.green)
Group.new('javascriptSymbolStaticMethod', c.green)
Group.new('javascriptRegExpMethod', c.green)
Group.new('javascriptObjectStaticMethod', c.green)
Group.new('javascriptObjectMethod', c.green)
Group.new('javascriptBOMLocationMethod', c.green)
Group.new('javascriptJSONStaticMethod', c.green)
Group.new('javascriptGeneratorMethod', c.green)
Group.new('javascriptEncodingMethod', c.green)
Group.new('javascriptPromiseStaticMethod', c.green)
Group.new('javascriptPromiseMethod', c.green)
Group.new('javascriptBOMHistoryMethod', c.green)
Group.new('javascriptDOMFormMethod', c.green)
Group.new('javascriptClipboardMethod', c.green)
Group.new('javascriptTypedArrayStaticMethod', c.green)
Group.new('javascriptBroadcastMethod', c.green)
Group.new('javascriptDateStaticMethod', c.green)
Group.new('javascriptDateMethod', c.green)
Group.new('javascriptConsoleMethod', c.green)
Group.new('javascriptArrayStaticMethod', c.green)
Group.new('javascriptArrayMethod', c.green)
Group.new('javascriptMathStaticMethod', c.green)
Group.new('javascriptSubtleCryptoMethod', c.green)
Group.new('javascriptCryptoMethod', c.green)
Group.new('javascriptProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBOMWindowProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptDOMStorageProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptFileReaderProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptURLUtilsProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptNumberStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptDOMNodeProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptRequestProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptResponseProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptES6SetProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptPaymentProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptPaymentResponseProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptPaymentAddressProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptPaymentShippingOptionProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptTypedArrayStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptServiceWorkerProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptES6MapProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptRegExpStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptRegExpProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptXHRProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBOMNavigatorProp', c.green)
Group.new('javascriptDOMEventProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBOMNetworkProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptDOMDocProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptSymbolStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptSymbolProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBOMLocationProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptEncodingProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptCryptoProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBOMHistoryProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptDOMFormProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptDataViewProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptBroadcastProp', g.Fg, g.Fg, g.Fg)
Group.new('javascriptMathStaticProp', g.Fg, g.Fg, g.Fg)

Group.new('jsxTagName', g.RedItalic, g.RedItalic, g.RedItalic)
Group.new('jsxOpenPunct', c.green)
Group.new('jsxClosePunct', c.blue)
Group.new('jsxEscapeJs', c.purple)
Group.new('jsxAttrib', c.blue)

Group.new('typescriptStorageClass', c.red)
Group.new('typescriptEndColons', g.Fg, g.Fg, g.Fg)
Group.new('typescriptSource', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptMessage', c.green)
Group.new('typescriptGlobalObjects', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptInterpolation', c.purple)
Group.new('typescriptInterpolationDelimiter', c.purple)
Group.new('typescriptBraces', g.Fg, g.Fg, g.Fg)
Group.new('typescriptParens', g.Fg, g.Fg, g.Fg)

Group.new('typescriptMethodAccessor', c.red)
Group.new('typescriptVariable', c.red)
Group.new('typescriptVariableDeclaration', g.Fg, g.Fg, g.Fg)
Group.new('typescriptTypeReference', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptBraces', g.Fg, g.Fg, g.Fg)
Group.new('typescriptEnumKeyword', c.red)
Group.new('typescriptEnum', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptIdentifierName', g.Fg, g.Fg, g.Fg)
Group.new('typescriptProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptCall', g.Fg, g.Fg, g.Fg)
Group.new('typescriptInterfaceName', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptEndColons', g.Fg, g.Fg, g.Fg)
Group.new('typescriptMember', g.Fg, g.Fg, g.Fg)
Group.new('typescriptMemberOptionality', c.red)
Group.new('typescriptObjectLabel', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDefaultParam', g.Fg, g.Fg, g.Fg)
Group.new('typescriptArrowFunc', c.red)
Group.new('typescriptAbstract', c.red)
Group.new('typescriptObjectColon', c.grey)
Group.new('typescriptTypeAnnotation', c.grey)
Group.new('typescriptAssign', c.red)
Group.new('typescriptBinaryOp', c.red)
Group.new('typescriptUnaryOp', c.red)
Group.new('typescriptFuncComma', g.Fg, g.Fg, g.Fg)
Group.new('typescriptClassName', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptClassHeritage', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptInterfaceHeritage', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptIdentifier', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('typescriptGlobal', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptOperator', c.red)
Group.new('typescriptNodeGlobal', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptExport', c.red)
Group.new('typescriptImport', c.red)
Group.new('typescriptTypeParameter', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('typescriptReadonlyModifier', c.red)
Group.new('typescriptAccessibilityModifier', c.red)
Group.new('typescriptAmbientDeclaration', c.red)
Group.new('typescriptTemplateSubstitution', c.purple)
Group.new('typescriptTemplateSB', c.purple)
Group.new('typescriptExceptions', c.red)
Group.new('typescriptCastKeyword', c.red)
Group.new('typescriptOptionalMark', c.red)
Group.new('typescriptNull', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('typescriptMappedIn', c.red)
Group.new('typescriptFuncTypeArrow', c.red)
Group.new('typescriptTernaryOp', c.red)
Group.new('typescriptParenExp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptIndexExpr', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDotNotation', c.grey)
Group.new('typescriptGlobalNumberDot', c.grey)
Group.new('typescriptGlobalStringDot', c.grey)
Group.new('typescriptGlobalArrayDot', c.grey)
Group.new('typescriptGlobalObjectDot', c.grey)
Group.new('typescriptGlobalSymbolDot', c.grey)
Group.new('typescriptGlobalMathDot', c.grey)
Group.new('typescriptGlobalDateDot', c.grey)
Group.new('typescriptGlobalJSONDot', c.grey)
Group.new('typescriptGlobalRegExpDot', c.grey)
Group.new('typescriptGlobalPromiseDot', c.grey)
Group.new('typescriptGlobalURLDot', c.grey)
Group.new('typescriptGlobalMethod', c.green)
Group.new('typescriptDOMStorageMethod', c.green)
Group.new('typescriptFileMethod', c.green)
Group.new('typescriptFileReaderMethod', c.green)
Group.new('typescriptFileListMethod', c.green)
Group.new('typescriptBlobMethod', c.green)
Group.new('typescriptURLStaticMethod', c.green)
Group.new('typescriptNumberStaticMethod', c.green)
Group.new('typescriptNumberMethod', c.green)
Group.new('typescriptDOMNodeMethod', c.green)
Group.new('typescriptPaymentMethod', c.green)
Group.new('typescriptPaymentResponseMethod', c.green)
Group.new('typescriptHeadersMethod', c.green)
Group.new('typescriptRequestMethod', c.green)
Group.new('typescriptResponseMethod', c.green)
Group.new('typescriptES6SetMethod', c.green)
Group.new('typescriptReflectMethod', c.green)
Group.new('typescriptBOMWindowMethod', c.green)
Group.new('typescriptGeolocationMethod', c.green)
Group.new('typescriptServiceWorkerMethod', c.green)
Group.new('typescriptCacheMethod', c.green)
Group.new('typescriptES6MapMethod', c.green)
Group.new('typescriptFunctionMethod', c.green)
Group.new('typescriptRegExpMethod', c.green)
Group.new('typescriptXHRMethod', c.green)
Group.new('typescriptBOMNavigatorMethod', c.green)
Group.new('typescriptServiceWorkerMethod', c.green)
Group.new('typescriptIntlMethod', c.green)
Group.new('typescriptDOMEventTargetMethod', c.green)
Group.new('typescriptDOMEventMethod', c.green)
Group.new('typescriptDOMDocMethod', c.green)
Group.new('typescriptStringStaticMethod', c.green)
Group.new('typescriptStringMethod', c.green)
Group.new('typescriptSymbolStaticMethod', c.green)
Group.new('typescriptObjectStaticMethod', c.green)
Group.new('typescriptObjectMethod', c.green)
Group.new('typescriptJSONStaticMethod', c.green)
Group.new('typescriptEncodingMethod', c.green)
Group.new('typescriptBOMLocationMethod', c.green)
Group.new('typescriptPromiseStaticMethod', c.green)
Group.new('typescriptPromiseMethod', c.green)
Group.new('typescriptSubtleCryptoMethod', c.green)
Group.new('typescriptCryptoMethod', c.green)
Group.new('typescriptBOMHistoryMethod', c.green)
Group.new('typescriptDOMFormMethod', c.green)
Group.new('typescriptConsoleMethod', c.green)
Group.new('typescriptDateStaticMethod', c.green)
Group.new('typescriptDateMethod', c.green)
Group.new('typescriptArrayStaticMethod', c.green)
Group.new('typescriptArrayMethod', c.green)
Group.new('typescriptMathStaticMethod', c.green)
Group.new('typescriptStringProperty', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDOMStorageProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptFileReaderProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptURLUtilsProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptNumberStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDOMNodeProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptBOMWindowProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptRequestProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptResponseProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptPaymentProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptPaymentResponseProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptPaymentAddressProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptPaymentShippingOptionProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptES6SetProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptServiceWorkerProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptES6MapProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptRegExpStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptRegExpProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptBOMNavigatorProp', c.green)
Group.new('typescriptXHRProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDOMEventProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDOMDocProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptBOMNetworkProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptSymbolStaticProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptEncodingProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptBOMLocationProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptCryptoProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptDOMFormProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptBOMHistoryProp', g.Fg, g.Fg, g.Fg)
Group.new('typescriptMathStaticProp', g.Fg, g.Fg, g.Fg)

Group.new('cLabel', c.red)
Group.new('cppSTLnamespace', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('cppSTLtype', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('cppAccess', c.red)
Group.new('cppStructure', c.red)
Group.new('cppSTLios', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('cppSTLiterator', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('cppSTLexception', c.red)

Group.new('objcModuleImport', c.red)
Group.new('objcException', c.red)
Group.new('objcProtocolList', c.fg)
Group.new('objcDirective', c.red)
Group.new('objcPropertyAttribute', c.purple)
Group.new('objcHiddenArgument', g.Fg, g.Fg, g.Fg)

Group.new('csUnspecifiedStatement', c.red)
Group.new('csStorage', c.red)
Group.new('csClass', c.red)
Group.new('csNewType', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('csContextualStatement', c.red)
Group.new('csInterpolationDelimiter', c.purple)
Group.new('csInterpolation', c.purple)
Group.new('csEndColon', g.Fg, g.Fg, g.Fg)

Group.new('pythonBuiltin', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('pythonExceptions', c.red)
Group.new('pythonDecoratorName', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('pythonExClass', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('pythonBuiltinType', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('pythonBuiltinObj', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('pythonDottedName', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('pythonBuiltinFunc', c.green)
Group.new('pythonFunction', c.green)
Group.new('pythonDecorator', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('pythonInclude', g.Include, g.Include, g.Include)
Group.new('pythonImport', g.PreProc, g.PreProc, g.PreProc)
Group.new('pythonOperator', c.red)
Group.new('pythonConditional', c.red)
Group.new('pythonRepeat', c.red)
Group.new('pythonException', c.red)
Group.new('pythonNone', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('pythonCoding', c.grey)
Group.new('pythonDot', c.grey)

Group.new('luaFunc', c.green)
Group.new('luaFunction', c.red)
Group.new('luaTable', g.Fg, g.Fg, g.Fg)
Group.new('luaIn', c.red)
Group.new('luaFuncCall', c.green)
Group.new('luaLocal', c.red)
Group.new('luaSpecialValue', c.green)
Group.new('luaBraces', g.Fg, g.Fg, g.Fg)
Group.new('luaBuiltIn', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('luaNoise', c.grey)
Group.new('luaLabel', c.purple)
Group.new('luaFuncTable', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('luaFuncArgName', g.Fg, g.Fg, g.Fg)
Group.new('luaEllipsis', c.red)
Group.new('luaDocTag', c.green)

Group.new('javaClassDecl', c.red)
Group.new('javaMethodDecl', c.red)
Group.new('javaVarArg', g.Fg, g.Fg, g.Fg)
Group.new('javaAnnotation', c.purple)
Group.new('javaUserLabel', c.purple)
Group.new('javaTypedef', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('javaParen', g.Fg, g.Fg, g.Fg)
Group.new('javaParen1', g.Fg, g.Fg, g.Fg)
Group.new('javaParen2', g.Fg, g.Fg, g.Fg)
Group.new('javaParen3', g.Fg, g.Fg, g.Fg)
Group.new('javaParen4', g.Fg, g.Fg, g.Fg)
Group.new('javaParen5', g.Fg, g.Fg, g.Fg)

Group.new('ktSimpleInterpolation', c.purple)
Group.new('ktComplexInterpolation', c.purple)
Group.new('ktComplexInterpolationBrace', c.purple)
Group.new('ktStructure', c.red)
Group.new('ktKeyword', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)

Group.new('rustStructure', c.red)
Group.new('rustIdentifier', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('rustModPath', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('rustModPathSep', c.grey)
Group.new('rustSelf', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('rustSuper', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('rustDeriveTrait', c.purple)
Group.new('rustEnumVariant', c.purple)
Group.new('rustMacroVariable', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('rustAssert', c.green)
Group.new('rustPanic', c.green)
Group.new('rustPubScopeCrate', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('rustAttribute', c.purple)

Group.new('swiftInterpolatedWrapper', c.purple)
Group.new('swiftInterpolatedString', c.purple)
Group.new('swiftProperty', g.Fg, g.Fg, g.Fg)
Group.new('swiftTypeDeclaration', c.red)
Group.new('swiftClosureArgument', g.OrangeItalic, g.OrangeItalic, g.OrangeItalic)
Group.new('swiftStructure', c.red)

Group.new('shRange', g.Fg, g.Fg, g.Fg)
Group.new('shOption', c.purple)
Group.new('shQuote', c.yellow)
Group.new('shVariable', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('shDerefSimple', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('shDerefVar', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('shDerefSpecial', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('shDerefOff', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('shVarAssign', c.red)
Group.new('shFunctionOne', c.green)
Group.new('shFunctionKey', c.red)

Group.new('zshOption', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('zshSubst', c.orange)
Group.new('zshFunction', c.green)

Group.new('vimnotfunc', c.red)
Group.new('vimcommand', c.red)
Group.new('vimCommentTitle', c.grey, nil, s.bold)
Group.new('vimLet', c.red)
Group.new('vimFunction', c.green)
Group.new('vimIsCommand', g.Fg, g.Fg, g.Fg)
Group.new('vimUserFunc', c.green)
Group.new('vimFuncName', c.green)
Group.new('vimMap', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('vimNotation', c.purple)
Group.new('vimMapLhs', c.green)
Group.new('vimMapRhs', c.green)
Group.new('vimSetEqual', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('vimSetSep', g.Fg, g.Fg, g.Fg)
Group.new('vimOption', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('vimUserAttrbKey', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('vimUserAttrb', c.green)
Group.new('vimAutoCmdSfxList', c.orange)
Group.new('vimSynType', c.orange)
Group.new('vimHiBang', c.orange)
Group.new('vimSet', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('vimSetSep', c.grey)

Group.new('makeIdent', c.purple)
Group.new('makeSpecTarget', g.BlueItalic, g.BlueItalic, g.BlueItalic)
Group.new('makeTarget', c.orange)
Group.new('makeCommands', c.red)

Group.new('jsonKeyword', c.red)
Group.new('jsonString', c.green)
Group.new('jsonBoolean', c.blue)
Group.new('jsonNoise', c.grey)
Group.new('jsonQuote', c.grey)
Group.new('jsonBraces', g.Fg, g.Fg, g.Fg)

Group.new('diffAdded', c.green)
Group.new('diffRemoved', c.red)
Group.new('diffChanged', c.blue)
Group.new('diffOldFile', c.yellow)
Group.new('diffNewFile', c.orange)
Group.new('diffFile', c.purple)
Group.new('diffLine', c.grey)
Group.new('diffIndexLine', c.purple)

Group.new('gitcommitSummary', c.red)
Group.new('gitcommitUntracked', c.grey)
Group.new('gitcommitDiscarded', c.grey)
Group.new('gitcommitSelected', c.grey)
Group.new('gitcommitUnmerged', c.grey)
Group.new('gitcommitOnBranch', c.grey)
Group.new('gitcommitArrow', c.grey)
Group.new('gitcommitFile', c.green)

Group.new('helpNote', c.purple, c.none, s.bold)
Group.new('helpHeadline', c.red, c.none, s.bold)
Group.new('helpHeader', c.orange, c.none, s.bold)
Group.new('helpURL', c.green, c.none, s.underline)
Group.new('helpHyperTextEntry', c.blue, c.none, s.bold)
Group.new('helpHyperTextJump', c.blue)
Group.new('helpCommand', c.yellow)
Group.new('helpExample', c.green)
Group.new('helpSpecial', c.purple)
Group.new('helpSectionDelim', c.grey)

Group.new('DashboardHeader', c.red, c.none)
Group.new('DashboardCenter', c.blue, c.none)
