-- Tries to load colorscheme twice if syntax on or syntax enable is not set in config
-- Syntax on or syntax enable in config messes with treesitter after my reload function
-- Live changing of colors with luafile won't work. Using lua require('seblj.utils').reload_config()
if Loaded_colorscheme then return end
Loaded_colorscheme = true

vim.g.colors_name = 'custom'

local highlight = function(name, opts)
    if not opts.guisp then opts.guisp = 'NONE' end
    if not opts.gui then opts.gui = 'NONE' end
    if name and vim.tbl_count(opts) > 0 then
        if opts.link and opts.link ~= "" then
            vim.cmd("highlight!" .. " link " .. name .. " " .. opts.link)
        else
            local cmd = {"highlight!", name}
            for k, v in pairs(opts) do
                table.insert(cmd, string.format("%s=", k) .. v)
            end
            vim.cmd(table.concat(cmd, " "))
        end
    end
end

local all = function(hls)
    for _, hl in ipairs(hls) do
        highlight(unpack(hl))
    end
end

---------- COLORS ----------

local c = {
    bg = '#1c1c1c',
    bg2 = '#363944',
    fg = '#eeeeee',
    error = '#ff0033',
    diff_red = '#55393d',
    diff_green = '#394634',
    diff_blue = '#354157',
    border = '#80A0C2',
    red = '#fc5d7c',
    orange = '#fea24f',
    yellow = '#e7c664',
    green = '#9ed072',
    blue = '#76cce0',
    purple = '#b39df3',
    grey = '#7f8490',
}

---------- GROUPS ----------

all {
    {'Normal', {guifg = c.fg, guibg = c.bg}},
    {'Terminal', {guifg = c.fg, guibg = c.bg}},
    {'EndOfBuffer', {guifg = c.bg, guibg = c.bg}},
    {'Folded', {guifg = c.grey, guibg = c.bg}},
    {'ToolbarLine', {guifg = c.fg, guibg = c.bg2}},
    {'SignColumn', {guifg = c.fg, guibg = 'NONE'}},
    {'FoldColumn', {guifg = c.grey, guibg = 'NONE'}},
    {'IncSearch', {guifg = c.bg, guibg = c.red}},
    {'Search', {guifg = c.bg, guibg = c.green}},
    {'ColorColumn', {guifg = 'NONE', guibg = c.bg}},
    {'Conceal', {guifg = c.grey, guibg = 'NONE'}},
    {'Cursor', {guifg = 'NONE', guibg = 'NONE', gui = 'reverse'}},

    {'vCursor', {link = 'Cursor'}},
    {'iCursor', {link = 'Cursor'}},
    {'lCursor', {link = 'Cursor'}},
    {'CursorIM', {link = 'Cursor'}},
    {'TransparentCursor', {gui = 'strikethrough', blend = 100}},

    {'CursorLine', {guifg = c.red, guibg = c.bg}},
    {'CursorColumn', {guifg = 'NONE', guibg = c.bg}},
    {'LineNr', {guifg = c.grey, guibg = 'NONE'}},
    {'CursorLineNr', {guifg = c.fg, guibg = 'NONE'}},

    {'DiffAdd', {guifg = 'NONE', guibg = c.diff_green}},
    {'DiffChange', {guifg = 'NONE', guibg = c.diff_blue}},
    {'DiffDelete', {guifg = 'NONE', guibg = c.diff_red}},
    {'DiffText', {guifg = c.bg, guibg = c.fg}},
    {'Directory', {guifg = c.green, guibg = 'NONE'}},
    {'ErrorMsg', {guifg = c.red, guibg = 'NONE'}},
    {'WarningMsg', {guifg = c.yellow, guibg = 'NONE', gui = 'bold'}},
    {'ModeMsg', {guifg = c.fg, guibg = 'NONE', gui = 'bold'}},
    {'MoreMsg', {guifg = c.blue, guibg = 'NONE', gui = 'bold'}},
    {'MatchParen', {guifg = 'NONE', guibg = c.bg2}},
    {'NonText', {guifg = c.bg2, guibg = 'NONE'}},
    {'Whitespace', {guifg = c.bg2, guibg = 'NONE'}},
    {'SpecialKey', {guifg = c.bg2, guibg = 'NONE'}},
    {'Pmenu', {guifg = c.fg, guibg = c.bg2}},
    {'PmenuSbar', {guifg = 'NONE', guibg = c.bg2}},
    {'PmenuSel', {guifg = c.bg, guibg = c.green}},
    {'WildMenu', {link = 'PmenuSel'}},

    {'PmenuThumb', {guifg = 'NONE', guibg = c.grey}},
    {'NormalFloat', {guifg = c.fg, guibg = c.bg2}},
    {'Question', {guifg = c.yellow, guibg = 'NONE'}},
    {'SpellBad', {guifg = c.red, guibg = 'NONE', gui = 'undercurl', guisp = c.red}},
    {'SpellCap', {guifg = c.yellow, guibg = 'NONE', gui = 'undercurl', guisp = c.yellow}},
    {'SpellLocal', {guifg = c.blue, guibg = 'NONE', gui = 'undercurl', guisp = c.blue}},
    {'SpellRare', {guifg = c.purple, guibg = 'NONE', gui = 'undercurl', guisp = c.purple}},
    {'StatusLine', {guifg = c.fg, guibg = 'NONE'}},
    {'StatusLineTerm', {guifg = c.fg, guibg = c.bg2}},
    {'StatusLineNC', {guifg = c.grey, guibg = c.bg}},
    {'StatusLineTermNC', {guifg = c.grey, guibg = c.bg}},
    {'TabLine', {guifg = 'NONE', guibg = c.yellow}},
    {'TabLineFill', {guifg = c.grey, guibg = c.bg}},
    {'TabLineSel', {guifg = 'NONE', guibg = c.red}},
    {'VertSplit', {guifg = c.grey, guibg = 'NONE'}},
    {'Visual', {guifg = 'NONE', guibg = c.bg2}},
    {'VisualNOS', {guifg = 'NONE', guibg = c.bg2, gui = 'underline'}},
    {'QuickFixLine', {guifg = c.blue, guibg = 'NONE', gui = 'bold'}},
    {'Debug', {guifg = c.yellow, guibg = 'NONE'}},
    {'debugPC', {guifg = c.bg, guibg = c.green}},
    {'debugBreakpoint', {guifg = c.bg, guibg = c.red}},
    {'ToolbarButton', {guifg = c.bg, guibg = c.blue}},

    {'ErrorText', {guifg = c.error, guibg = 'NONE', gui = 'undercurl', guisp = c.red}},
    {'WarningText', {guifg = c.orange, guibg = 'NONE', gui = 'undercurl', guisp = c.yellow}},
    {'InfoText', {guifg = c.yellow, guibg = 'NONE', gui = 'undercurl', guisp = c.blue}},
    {'HintText', {guifg = c.yellow, guibg = 'NONE', gui = 'undercurl', guisp = c.green}},
    {'ErrorFloat', {guifg = c.red, guibg = c.bg2}},
    {'WarningFloat', {guifg = c.yellow, guibg = c.bg2}},
    {'InfoFloat', {guifg = c.blue, guibg = c.bg2}},
    {'HintFloat', {guifg = c.green, guibg = c.bg2}},
    {'ErrorLine', {guifg = 'NONE', guibg = 'NONE'}},
    {'WarningLine', {guifg = 'NONE', guibg = 'NONE'}},
    {'InfoLine', {guifg = 'NONE', guibg = 'NONE'}},
    {'HintLine', {guifg = 'NONE', guibg = 'NONE'}},

    {'RedSign', {guifg = c.red, guibg = c.bg}},
    {'OrangeSign', {guifg = c.orange, guibg = c.bg}},
    {'YellowSign', {guifg = c.yellow, guibg = c.bg}},
    {'GreenSign', {guifg = c.green, guibg = c.bg}},
    {'BlueSign', {guifg = c.blue, guibg = c.bg}},
    {'PurpleSign', {guifg = c.purple, guibg = c.bg}},

    {'CurrentWord', {guifg = c.bg, guibg = c.green}},
    {'Substitute', {guifg = c.bg, guibg = c.yellow}},
    {'TermCursor', {link = 'Cursor'}},
    {'healthError', {guifg = c.red}},
    {'healthSuccess', {guifg = c.green}},
    {'healthWarning', {guifg = c.yellow}},

    {'Type', {guifg = c.blue, guibg = 'NONE'}},
    {'Structure', {guifg = c.blue, guibg = 'NONE'}},
    {'StorageClass', {guifg = c.blue, guibg = 'NONE'}},
    {'Identifier', {guifg = c.orange, guibg = 'NONE'}},
    {'Constant', {guifg = c.orange, guibg = 'NONE'}},

    {'PreProc', {guifg = c.red, guibg = 'NONE'}},
    {'PreCondit', {guifg = c.red, guibg = 'NONE'}},
    {'Include', {guifg = c.red, guibg = 'NONE'}},
    {'Keyword', {guifg = c.red, guibg = 'NONE'}},
    {'Define', {guifg = c.red, guibg = 'NONE'}},
    {'Typedef', {guifg = c.red, guibg = 'NONE'}},
    {'Exception', {guifg = c.red, guibg = 'NONE'}},
    {'Conditional', {guifg = c.red, guibg = 'NONE'}},
    {'Repeat', {guifg = c.red, guibg = 'NONE'}},
    {'Statement', {guifg = c.red, guibg = 'NONE'}},
    {'Macro', {guifg = c.purple, guibg = 'NONE'}},
    {'Error', {guifg = c.red, guibg = 'NONE'}},
    {'Label', {guifg = c.purple, guibg = 'NONE'}},
    {'Special', {guifg = c.purple, guibg = 'NONE'}},
    {'SpecialChar', {guifg = c.purple, guibg = 'NONE'}},
    {'Boolean', {guifg = c.purple, guibg = 'NONE'}},
    {'String', {guifg = c.yellow, guibg = 'NONE'}},
    {'Character', {guifg = c.yellow, guibg = 'NONE'}},
    {'Number', {guifg = c.purple, guibg = 'NONE'}},
    {'Float', {guifg = c.purple, guibg = 'NONE'}},
    {'Function', {guifg = c.green, guibg = 'NONE'}},
    {'Operator', {guifg = c.red, guibg = 'NONE'}},
    {'Title', {guifg = c.red, guibg = 'NONE', gui = 'bold'}},
    {'Tag', {guifg = c.orange, guibg = 'NONE'}},
    {'Delimiter', {guifg = c.fg, guibg = 'NONE'}},

    {'Comment', {guifg = c.grey, guibg = 'NONE', gui = 'italic'}},
    {'SpecialComment', {guifg = c.grey, guibg = 'NONE', gui = 'italic'}},
    {'Todo', {guifg = c.blue, guibg = 'NONE', gui = 'italic'}},

    {'Ignore', {guifg = c.grey, guibg = 'NONE'}},
    {'Underlined', {guifg = 'NONE', guibg = 'NONE', gui = 'underline'}},

    ---------- TREESITTER ----------

    {'TSAnnotation', {guifg = c.blue}},
    {'TSAttribute', {guifg = c.blue}},
    {'TSBoolean', {guifg = c.purple}},
    {'TSCharacter', {guifg = c.yellow}},
    {'TSComment', {guifg = c.grey}},
    {'TSConditional', {guifg = c.red}},
    {'TSConstBuiltin', {guifg = c.orange}},
    {'TSConstMacro', {guifg = c.orange}},
    {'TSConstant', {guifg = c.orange}},
    {'TSConstructor', {guifg = c.fg}},
    {'TSCustomType', {guifg = c.purple}},
    {'TSError', {link = 'Normal'}},
    {'TSException', {guifg = c.red}},
    {'TSField', {guifg = c.green}},
    {'TSFloat', {guifg = c.purple}},
    {'TSFuncBuiltin', {guifg = c.green}},
    {'TSFuncMacro', {guifg = c.green}},
    {'TSFunction', {guifg = c.green}},
    {'TSInclude', {guifg = c.blue}},
    {'TSKeyword', {guifg = c.red}},
    {'TSKeywordFunction', {guifg = c.red}},
    {'TSLabel', {guifg = c.red}},
    {'TSMethod', {guifg = c.green}},
    {'TSNamespace', {guifg = c.purple}},
    {'TSNumber', {guifg = c.purple}},
    {'TSOperator', {guifg = c.red}},
    {'TSParameter', {link = 'NONE'}},
    {'TSParameterReference', {guifg = c.orange}},
    {'TSProperty', {guifg = c.green}},
    {'cTSProperty', {link = 'NONE'}},
    {'TSPunctBracket', {guifg = c.fg}},
    {'TSPunctDelimiter', {guifg = c.grey}},
    {'TSPunctSpecial', {guifg = c.fg}},
    {'TSRepeat', {guifg = c.red}},
    {'TSString', {guifg = c.yellow}},
    {'TSStringEscape', {guifg = c.yellow}},
    {'TSStringRegex', {guifg = c.green}},
    {'TSStructure', {guifg = c.blue}},
    {'TSTag', {guifg = c.blue}},
    {'TSTagDelimiter', {guifg = c.red}},
    {'TSText', {guifg = c.green}},
    {'TSEmphasis', {guifg = 'NONE', guibg = 'NONE', gui = 'bold'}},
    -- {'TSUnderline', {guifg = 'NONE', guibg = 'NONE', gui = 'underline'}},
    {'TSType', {guifg = c.blue}},
    {'TSTypeBuiltin', {guifg = c.blue}},
    {'TSURI', {guifg = c.blue, guibg = 'NONE', gui = 'underline'}},
    {'TSVariable', {guifg = c.fg}},
    {'TSVariableBuiltin', {guifg = c.orange}},

    ---------- COC ----------

    -- {'CocHoverRange', {guifg = 'NONE', guibg = 'NONE', gui = 'bold,underline'}},
    {'CocErrorFloat', {link = 'ErrorFloat'}},
    {'CocWarningFloat', {link = 'WarningFloat'}},
    {'CocInfoFloat', {link = 'InfoFloat'}},
    {'CocHintFloat', {link = 'HintFloat'}},
    {'CocErrorHighlight', {link = 'ErrorText'}},
    {'CocWarningHighlight', {link = 'WarningText'}},
    {'CocInfoHighlight', {link = 'InfoText'}},
    {'CocHintHighlight', {link = 'HintText'}},
    {'CocHighlightText', {link = 'CurrentWord'}},
    {'CocErrorSign', {link = 'RedSign'}},
    {'CocWarningSign', {link = 'OrangeSign'}},
    {'CocInfoSign', {link = 'BlueSign'}},
    {'CocHintSign', {link = 'YellowSign'}},
    {'CocWarningVirtualText', {guifg = c.grey}},
    {'CocErrorVirtualText', {guifg = c.grey}},
    {'CocInfoVirtualText', {guifg = c.grey}},
    {'CocHintVirtualText', {guifg = c.grey}},
    {'CocErrorLine', {link = 'ErrorLine'}},
    {'CocWarningLine', {link = 'WarningLine'}},
    {'CocInfoLine', {link = 'InfoLine'}},
    {'CocHintLine', {link = 'HintLine'}},
    {'CocCodeLens', {guifg = c.grey}},
    {'HighlightedyankRegion', {link = 'Visual'}},
    {'CocGitAddedSign', {link = 'GreenSign'}},
    {'CocGitChangeRemovedSign', {link = 'PurpleSign'}},
    {'CocGitChangedSign', {link = 'BlueSign'}},
    {'CocGitRemovedSign', {link = 'RedSign'}},
    {'CocGitTopRemovedSign', {link = 'RedSign'}},
    {'CocExplorerBufferRoot', {guifg = c.red}},
    {'CocExplorerBufferExpandIcon', {guifg = c.blue}},
    {'CocExplorerBufferBufnr', {guifg = c.yellow}},
    {'CocExplorerBufferModified', {guifg = c.yellow}},
    {'CocExplorerBufferReadonly', {guifg = c.red}},
    {'CocExplorerBufferBufname', {guifg = c.grey}},
    {'CocExplorerBufferFullpath', {guifg = c.grey}},
    {'CocExplorerFileRoot', {guifg = c.red}},
    {'CocExplorerFileRootName', {guifg = c.green}},
    {'CocExplorerFileExpandIcon', {guifg = c.blue}},
    {'CocExplorerFileFullpath', {guifg = c.grey}},
    {'CocExplorerFileDirectory', {guifg = c.green}},
    {'CocExplorerFileGitStaged', {guifg = c.purple}},
    {'CocExplorerFileGitUnstaged', {guifg = c.yellow}},
    {'CocExplorerFileGitRootStaged', {guifg = c.purple}},
    {'CocExplorerFileGitRootUnstaged', {guifg = c.yellow}},
    {'CocExplorerGitPathChange', {guifg = c.fg}},
    {'CocExplorerGitContentChange', {guifg = c.fg}},
    {'CocExplorerGitRenamed', {guifg = c.purple}},
    {'CocExplorerGitCopied', {guifg = c.fg}},
    {'CocExplorerGitAdded', {guifg = c.green}},
    {'CocExplorerGitUntracked', {guifg = c.blue}},
    {'CocExplorerGitUnmodified', {guifg = c.fg}},
    {'CocExplorerGitUnmerged', {guifg = c.orange}},
    {'CocExplorerGitMixed', {guifg = c.fg}},
    {'CocExplorerGitModified', {guifg = c.yellow}},
    {'CocExplorerGitDeleted', {guifg = c.red}},
    {'CocExplorerGitIgnored', {guifg = c.grey}},
    {'CocExplorerFileSize', {guifg = c.blue}},
    {'CocExplorerTimeAccessed', {guifg = c.purple}},
    {'CocExplorerTimeCreated', {guifg = c.purple}},
    {'CocExplorerTimeModified', {guifg = c.purple}},
    {'CocExplorerFileRootName', {guifg = c.orange}},
    {'CocExplorerBufferNameVisible', {guifg = c.green}},
    {'CocExplorerIndentLine', {link = 'Conceal'}},
    {'CocExplorerHelpDescription', {guifg = c.grey}},
    {'CocExplorerHelpHint', {guifg = c.grey}},

    ---------- NVIM LSPCONFIG ----------

    {'LspDiagnosticsFloatingError', {guifg = c.red, guibg = 'NONE'}},
    {'LspDiagnosticsFloatingWarning', {guifg = c.orange, guibg = 'NONE'}},
    {'LspDiagnosticsFloatingInformation', {guifg = c.yellow, guibg = 'NONE'}},
    {'LspDiagnosticsFloatingHint', {guifg = c.fg, guibg = 'NONE'}},
    {'LspDiagnosticsDefaultError', {link = 'ErrorText'}},
    {'LspDiagnosticsDefaultWarning', {link = 'WarningText'}},
    {'LspDiagnosticsDefaultInformation', {link = 'InfoText'}},
    {'LspDiagnosticsDefaultHint', {link = 'HintText'}},
    {'LspDiagnosticsVirtualTextError', {guifg = c.red}},
    {'LspDiagnosticsVirtualTextWarning', {guifg = c.orange}},
    {'LspDiagnosticsVirtualTextInformation', {guifg = c.yellow}},
    {'LspDiagnosticsVirtualTextHint', {guifg = c.yellow}},
    {'LspDiagnosticsUnderlineError', {link = 'ErrorText'}},
    {'LspDiagnosticsUnderlineWarning', {link = 'WarningText'}},
    {'LspDiagnosticsUnderlineInformation', {link = 'InfoText'}},
    {'LspDiagnosticsUnderlineHint', {link = 'HintText'}},
    {'LspDiagnosticsSignError', {link = 'RedSign'}},
    {'LspDiagnosticsSignWarning', {link = 'OrangeSign'}},
    {'LspDiagnosticsSignInformation', {link = 'BlueSign'}},
    {'LspDiagnosticsSignHint', {link = 'YellowSign'}},
    {'LspReferenceText', {link = 'CurrentWord'}},
    {'LspReferenceRead', {link = 'CurrentWord'}},
    {'LspReferenceWrite', {link = 'CurrentWord'}},

    ---------- LSPSAGA ----------

    {'LspSagaDiagnosticBorder', {guifg = c.border}},
    {'LspSagaDiagnosticTruncateLine', {guifg = c.border}},
    {'LspSagaDiagnosticHeader', {guifg = c.fg}},
    {'LspSagaRenameBorder', {guifg = c.border}},
    {'LspSagaHoverBorder', {guifg = c.border}},
    {'LspSagaCodeActionBorder', {guifg = c.border}},
    {'LspSagaSignatureHelpBorder', {guifg = c.border}},

    ---------- GITSIGNS ----------

    {'GitGutterAdd', {link = 'GreenSign'}},
    {'GitGutterChange', {link = 'BlueSign'}},
    {'GitGutterDelete', {link = 'RedSign'}},
    {'GitGutterChangeDelete', {link = 'PurpleSign'}},

    ---------- MULTIPLE CURSORS ----------

    {'multiple_cursors_cursor', {link = 'Cursor'}},
    {'multiple_cursors_visual', {link = 'Visual'}},

    ---------- VIM PLUG ----------

    {'plug1', {guifg = c.red, guibg = 'NONE', gui = 'bold'}},
    {'plugNumber', {guifg = c.yellow, guibg = 'NONE', gui = 'bold'}},
    {'plug2', {guifg = c.blue}},
    {'plugBracket', {guifg = c.blue}},
    {'plugName', {guifg = c.green}},
    {'plugDash', {guifg = c.red}},
    {'plugNotLoaded', {guifg = c.grey}},
    {'plugH2', {guifg = c.purple}},
    {'plugMessage', {guifg = c.purple}},
    {'plugError', {guifg = c.red}},
    {'plugRelDate', {guifg = c.grey}},
    {'plugStar', {guifg = c.purple}},
    {'plugUpdate', {guifg = c.blue}},
    {'plugDeleted', {guifg = c.grey}},
    {'plugEdge', {guifg = c.purple}},

    ---------- TEX ----------

    {'texStatement', {guifg = c.blue}},
    {'texOnlyMath', {guifg = c.grey}},
    {'texDefName', {guifg = c.yellow}},
    {'texNewCmd', {guifg = c.orange}},
    {'texCmdName', {guifg = c.blue}},
    {'texBeginEnd', {guifg = c.red}},
    {'texBeginEndName', {guifg = c.green}},
    {'texDocType', {guifg = c.red}},
    {'texDocTypeArgs', {guifg = c.orange}},
    {'texInputFile', {guifg = c.green}},
    {'texFileArg', {guifg = c.green}},
    {'texCmd', {guifg = c.blue}},
    {'texCmdPackage', {guifg = c.blue}},
    {'texCmdDef', {guifg = c.red}},
    {'texDefArgName', {guifg = c.yellow}},
    {'texCmdNewcmd', {guifg = c.red}},
    {'texCmdClass', {guifg = c.red}},
    {'texCmdTitle', {guifg = c.red}},
    {'texCmdAuthor', {guifg = c.red}},
    {'texCmdEnv', {guifg = c.red}},
    {'texCmdPart', {guifg = c.red}},
    {'texEnvArgName', {guifg = c.green}},

    ---------- HTML ----------

    {'htmlH1', {guifg = c.red, guibg = 'NONE', gui = 'bold'}},
    {'htmlH2', {guifg = c.orange, guibg = 'NONE', gui = 'bold'}},
    {'htmlH3', {guifg = c.yellow, guibg = 'NONE', gui = 'bold'}},
    {'htmlH4', {guifg = c.green, guibg = 'NONE', gui = 'bold'}},
    {'htmlH5', {guifg = c.blue, guibg = 'NONE', gui = 'bold'}},
    {'htmlH6', {guifg = c.purple, guibg = 'NONE', gui = 'bold'}},
    {'htmlLink', {guifg = 'NONE', guibg = 'NONE', gui = 'underline'}},
    {'htmlBold', {guifg = 'NONE', guibg = 'NONE', gui = 'bold'}},
    {'htmlBoldUnderline', {guifg = 'NONE', guibg = 'NONE', gui = 'bold,underline'}},
    {'htmlBoldItalic', {guifg = 'NONE', guibg = 'NONE', gui = 'bold,italic'}},
    {'htmlBoldUnderlineItalic', {guifg = 'NONE', guibg = 'NONE', gui = 'bold,underline,italic'}},
    {'htmlUnderline', {guifg = 'NONE', guibg = 'NONE', gui = 'underline'}},
    {'htmlUnderlineItalic', {guifg = 'NONE', guibg = 'NONE', gui = 'underline,italic'}},
    {'htmlItalic', {guifg = 'NONE', guibg = 'NONE', gui = 'italic'}},

    {'htmlTag', {guifg = c.green}},
    {'htmlEndTag', {guifg = c.blue}},
    {'htmlTagN', {guifg = c.red}},
    {'htmlTagName', {guifg = c.red}},
    {'htmlArg', {guifg = c.blue}},
    {'htmlScriptTag', {guifg = c.purple}},
    {'htmlSpecialTagName', {guifg = c.red}},
    {'htmlString', {guifg = c.green}},

    ---------- CSS ----------

    {'cssStringQ', {guifg = c.green}},
    {'cssStringQQ', {guifg = c.green}},
    {'cssAttrComma', {guifg = c.grey}},
    {'cssBraces', {guifg = c.grey}},
    {'cssTagName', {guifg = c.purple}},
    {'cssClassNameDot', {guifg = c.grey}},
    {'cssClassName', {guifg = c.red}},
    {'cssFunctionName', {guifg = c.orange}},
    {'cssAttr', {guifg = c.green}},
    {'cssCommonAttr', {guifg = c.green}},
    {'cssProp', {guifg = c.blue}},
    {'cssPseudoClassId', {guifg = c.yellow}},
    {'cssPseudoClassFn', {guifg = c.green}},
    {'cssPseudoClass', {guifg = c.yellow}},
    {'cssImportant', {guifg = c.red}},
    {'cssSelectorOp', {guifg = c.orange}},
    {'cssSelectorOp2', {guifg = c.orange}},
    {'cssColor', {guifg = c.green}},
    {'cssUnitDecorators', {guifg = c.green}},
    {'cssValueLength', {guifg = c.green}},
    {'cssValueInteger', {guifg = c.green}},
    {'cssValueNumber', {guifg = c.green}},
    {'cssValueAngle', {guifg = c.green}},
    {'cssValueTime', {guifg = c.green}},
    {'cssValueFrequency', {guifg = c.green}},
    {'cssVendor', {guifg = c.grey}},
    {'cssNoise', {guifg = c.grey}},

    ---------- LESS ----------

    {'lessMixinChar', {guifg = c.grey}},
    {'lessClass', {guifg = c.red}},
    {'lessFunction', {guifg = c.orange}},

    ---------- JAVASCRIPT / JSX ----------

    {'javaScriptNull', {guifg = c.orange}},
    {'javaScriptIdentifier', {guifg = c.blue}},
    {'javaScriptParens', {guifg = c.fg}},
    {'javaScriptBraces', {guifg = c.fg}},
    {'javaScriptNumber', {guifg = c.purple}},
    {'javaScriptLabel', {guifg = c.red}},
    {'javaScriptGlobal', {guifg = c.blue}},
    {'javaScriptMessage', {guifg = c.blue}},

    {'jsNoise', {guifg = c.fg}},
    {'Noise', {guifg = c.fg}},
    {'jsParens', {guifg = c.fg}},
    {'jsBrackets', {guifg = c.fg}},
    {'jsObjectBraces', {guifg = c.fg}},
    {'jsThis', {guifg = c.blue}},
    {'jsUndefined', {guifg = c.orange}},
    {'jsNull', {guifg = c.orange}},
    {'jsNan', {guifg = c.orange}},
    {'jsSuper', {guifg = c.orange}},
    {'jsPrototype', {guifg = c.orange}},
    {'jsFunction', {guifg = c.red}},
    {'jsGlobalNodeObjects', {guifg = c.blue}},
    {'jsGlobalObjects', {guifg = c.blue}},
    {'jsArrowFunction', {guifg = c.red}},
    {'jsArrowFuncArgs', {guifg = c.fg}},
    {'jsFuncArgs', {guifg = c.fg}},
    {'jsObjectProp', {guifg = c.fg}},
    {'jsVariableDef', {guifg = c.fg}},
    {'jsObjectKey', {guifg = c.fg}},
    {'jsParen', {guifg = c.fg}},
    {'jsParenIfElse', {guifg = c.fg}},
    {'jsParenRepeat', {guifg = c.fg}},
    {'jsParenSwitch', {guifg = c.fg}},
    {'jsParenCatch', {guifg = c.fg}},
    {'jsBracket', {guifg = c.fg}},
    {'jsObjectValue', {guifg = c.fg}},
    {'jsDestructuringBlock', {guifg = c.fg}},
    {'jsBlockLabel', {guifg = c.purple}},
    {'jsFunctionKey', {guifg = c.green}},
    {'jsClassDefinition', {guifg = c.blue}},
    {'jsDot', {guifg = c.grey}},
    {'jsSpreadExpression', {guifg = c.purple}},
    {'jsSpreadOperator', {guifg = c.green}},
    {'jsModuleKeyword', {guifg = c.blue}},
    {'jsTemplateExpression', {guifg = c.purple}},
    {'jsTemplateBraces', {guifg = c.purple}},
    {'jsClassMethodType', {guifg = c.blue}},
    {'jsExceptions', {guifg = c.blue}},

    {'javascriptOpSymbol', {guifg = c.red}},
    {'javascriptOpSymbols', {guifg = c.red}},
    {'javascriptIdentifierName', {guifg = c.fg}},
    {'javascriptVariable', {guifg = c.blue}},
    {'javascriptObjectLabel', {guifg = c.fg}},
    {'javascriptPropertyNameString', {guifg = c.fg}},
    {'javascriptFuncArg', {guifg = c.fg}},
    {'javascriptObjectLiteral', {guifg = c.green}},
    {'javascriptIdentifier', {guifg = c.orange}},
    {'javascriptArrowFunc', {guifg = c.red}},
    {'javascriptTemplate', {guifg = c.purple}},
    {'javascriptTemplateSubstitution', {guifg = c.purple}},
    {'javascriptTemplateSB', {guifg = c.purple}},
    {'javascriptNodeGlobal', {guifg = c.blue}},
    {'javascriptDocTags', {guifg = c.red}},
    {'javascriptDocNotation', {guifg = c.blue}},
    {'javascriptClassSuper', {guifg = c.orange}},
    {'javascriptClassName', {guifg = c.blue}},
    {'javascriptClassSuperName', {guifg = c.blue}},
    {'javascriptOperator', {guifg = c.red}},
    {'javascriptBrackets', {guifg = c.fg}},
    {'javascriptBraces', {guifg = c.fg}},
    {'javascriptLabel', {guifg = c.purple}},
    {'javascriptEndColons', {guifg = c.grey}},
    {'javascriptObjectLabelColon', {guifg = c.grey}},
    {'javascriptDotNotation', {guifg = c.grey}},
    {'javascriptGlobalArrayDot', {guifg = c.grey}},
    {'javascriptGlobalBigIntDot', {guifg = c.grey}},
    {'javascriptGlobalDateDot', {guifg = c.grey}},
    {'javascriptGlobalJSONDot', {guifg = c.grey}},
    {'javascriptGlobalMathDot', {guifg = c.grey}},
    {'javascriptGlobalNumberDot', {guifg = c.grey}},
    {'javascriptGlobalObjectDot', {guifg = c.grey}},
    {'javascriptGlobalPromiseDot', {guifg = c.grey}},
    {'javascriptGlobalRegExpDot', {guifg = c.grey}},
    {'javascriptGlobalStringDot', {guifg = c.grey}},
    {'javascriptGlobalSymbolDot', {guifg = c.grey}},
    {'javascriptGlobalURLDot', {guifg = c.grey}},
    {'javascriptMethod', {guifg = c.green}},
    {'javascriptMethodName', {guifg = c.green}},
    {'javascriptObjectMethodName', {guifg = c.green}},
    {'javascriptGlobalMethod', {guifg = c.green}},
    {'javascriptDOMStorageMethod', {guifg = c.green}},
    {'javascriptFileMethod', {guifg = c.green}},
    {'javascriptFileReaderMethod', {guifg = c.green}},
    {'javascriptFileListMethod', {guifg = c.green}},
    {'javascriptBlobMethod', {guifg = c.green}},
    {'javascriptURLStaticMethod', {guifg = c.green}},
    {'javascriptNumberStaticMethod', {guifg = c.green}},
    {'javascriptNumberMethod', {guifg = c.green}},
    {'javascriptDOMNodeMethod', {guifg = c.green}},
    {'javascriptES6BigIntStaticMethod', {guifg = c.green}},
    {'javascriptBOMWindowMethod', {guifg = c.green}},
    {'javascriptHeadersMethod', {guifg = c.green}},
    {'javascriptRequestMethod', {guifg = c.green}},
    {'javascriptResponseMethod', {guifg = c.green}},
    {'javascriptES6SetMethod', {guifg = c.green}},
    {'javascriptReflectMethod', {guifg = c.green}},
    {'javascriptPaymentMethod', {guifg = c.green}},
    {'javascriptPaymentResponseMethod', {guifg = c.green}},
    {'javascriptTypedArrayStaticMethod', {guifg = c.green}},
    {'javascriptGeolocationMethod', {guifg = c.green}},
    {'javascriptES6MapMethod', {guifg = c.green}},
    {'javascriptServiceWorkerMethod', {guifg = c.green}},
    {'javascriptCacheMethod', {guifg = c.green}},
    {'javascriptFunctionMethod', {guifg = c.green}},
    {'javascriptXHRMethod', {guifg = c.green}},
    {'javascriptBOMNavigatorMethod', {guifg = c.green}},
    {'javascriptServiceWorkerMethod', {guifg = c.green}},
    {'javascriptDOMEventTargetMethod', {guifg = c.green}},
    {'javascriptDOMEventMethod', {guifg = c.green}},
    {'javascriptIntlMethod', {guifg = c.green}},
    {'javascriptDOMDocMethod', {guifg = c.green}},
    {'javascriptStringStaticMethod', {guifg = c.green}},
    {'javascriptStringMethod', {guifg = c.green}},
    {'javascriptSymbolStaticMethod', {guifg = c.green}},
    {'javascriptRegExpMethod', {guifg = c.green}},
    {'javascriptObjectStaticMethod', {guifg = c.green}},
    {'javascriptObjectMethod', {guifg = c.green}},
    {'javascriptBOMLocationMethod', {guifg = c.green}},
    {'javascriptJSONStaticMethod', {guifg = c.green}},
    {'javascriptGeneratorMethod', {guifg = c.green}},
    {'javascriptEncodingMethod', {guifg = c.green}},
    {'javascriptPromiseStaticMethod', {guifg = c.green}},
    {'javascriptPromiseMethod', {guifg = c.green}},
    {'javascriptBOMHistoryMethod', {guifg = c.green}},
    {'javascriptDOMFormMethod', {guifg = c.green}},
    {'javascriptClipboardMethod', {guifg = c.green}},
    {'javascriptTypedArrayStaticMethod', {guifg = c.green}},
    {'javascriptBroadcastMethod', {guifg = c.green}},
    {'javascriptDateStaticMethod', {guifg = c.green}},
    {'javascriptDateMethod', {guifg = c.green}},
    {'javascriptConsoleMethod', {guifg = c.green}},
    {'javascriptArrayStaticMethod', {guifg = c.green}},
    {'javascriptArrayMethod', {guifg = c.green}},
    {'javascriptMathStaticMethod', {guifg = c.green}},
    {'javascriptSubtleCryptoMethod', {guifg = c.green}},
    {'javascriptCryptoMethod', {guifg = c.green}},
    {'javascriptProp', {guifg = c.fg}},
    {'javascriptBOMWindowProp', {guifg = c.fg}},
    {'javascriptDOMStorageProp', {guifg = c.fg}},
    {'javascriptFileReaderProp', {guifg = c.fg}},
    {'javascriptURLUtilsProp', {guifg = c.fg}},
    {'javascriptNumberStaticProp', {guifg = c.fg}},
    {'javascriptDOMNodeProp', {guifg = c.fg}},
    {'javascriptRequestProp', {guifg = c.fg}},
    {'javascriptResponseProp', {guifg = c.fg}},
    {'javascriptES6SetProp', {guifg = c.fg}},
    {'javascriptPaymentProp', {guifg = c.fg}},
    {'javascriptPaymentResponseProp', {guifg = c.fg}},
    {'javascriptPaymentAddressProp', {guifg = c.fg}},
    {'javascriptPaymentShippingOptionProp', {guifg = c.fg}},
    {'javascriptTypedArrayStaticProp', {guifg = c.fg}},
    {'javascriptServiceWorkerProp', {guifg = c.fg}},
    {'javascriptES6MapProp', {guifg = c.fg}},
    {'javascriptRegExpStaticProp', {guifg = c.fg}},
    {'javascriptRegExpProp', {guifg = c.fg}},
    {'javascriptXHRProp', {guifg = c.fg}},
    {'javascriptBOMNavigatorProp', {guifg = c.green}},
    {'javascriptDOMEventProp', {guifg = c.fg}},
    {'javascriptBOMNetworkProp', {guifg = c.fg}},
    {'javascriptDOMDocProp', {guifg = c.fg}},
    {'javascriptSymbolStaticProp', {guifg = c.fg}},
    {'javascriptSymbolProp', {guifg = c.fg}},
    {'javascriptBOMLocationProp', {guifg = c.fg}},
    {'javascriptEncodingProp', {guifg = c.fg}},
    {'javascriptCryptoProp', {guifg = c.fg}},
    {'javascriptBOMHistoryProp', {guifg = c.fg}},
    {'javascriptDOMFormProp', {guifg = c.fg}},
    {'javascriptDataViewProp', {guifg = c.fg}},
    {'javascriptBroadcastProp', {guifg = c.fg}},
    {'javascriptMathStaticProp', {guifg = c.fg}},

    {'jsxTagName', {guifg = c.red}},
    {'jsxOpenPunct', {guifg = c.green}},
    {'jsxClosePunct', {guifg = c.blue}},
    {'jsxEscapeJs', {guifg = c.purple}},
    {'jsxAttrib', {guifg = c.blue}},

    ---------- TYPESCRIPT / TSX ----------

    {'typescriptStorageClass', {guifg = c.red}},
    {'typescriptEndColons', {guifg = c.fg}},
    {'typescriptSource', {guifg = c.blue}},
    {'typescriptMessage', {guifg = c.green}},
    {'typescriptGlobalObjects', {guifg = c.blue}},
    {'typescriptInterpolation', {guifg = c.purple}},
    {'typescriptInterpolationDelimiter', {guifg = c.purple}},
    {'typescriptBraces', {guifg = c.fg}},
    {'typescriptParens', {guifg = c.fg}},

    {'typescriptMethodAccessor', {guifg = c.red}},
    {'typescriptVariable', {guifg = c.red}},
    {'typescriptVariableDeclaration', {guifg = c.fg}},
    {'typescriptTypeReference', {guifg = c.blue}},
    {'typescriptBraces', {guifg = c.fg}},
    {'typescriptEnumKeyword', {guifg = c.red}},
    {'typescriptEnum', {guifg = c.blue}},
    {'typescriptIdentifierName', {guifg = c.fg}},
    {'typescriptProp', {guifg = c.fg}},
    {'typescriptCall', {guifg = c.fg}},
    {'typescriptInterfaceName', {guifg = c.blue}},
    {'typescriptEndColons', {guifg = c.fg}},
    {'typescriptMember', {guifg = c.fg}},
    {'typescriptMemberOptionality', {guifg = c.red}},
    {'typescriptObjectLabel', {guifg = c.fg}},
    {'typescriptDefaultParam', {guifg = c.fg}},
    {'typescriptArrowFunc', {guifg = c.red}},
    {'typescriptAbstract', {guifg = c.red}},
    {'typescriptObjectColon', {guifg = c.grey}},
    {'typescriptTypeAnnotation', {guifg = c.grey}},
    {'typescriptAssign', {guifg = c.red}},
    {'typescriptBinaryOp', {guifg = c.red}},
    {'typescriptUnaryOp', {guifg = c.red}},
    {'typescriptFuncComma', {guifg = c.fg}},
    {'typescriptClassName', {guifg = c.blue}},
    {'typescriptClassHeritage', {guifg = c.blue}},
    {'typescriptInterfaceHeritage', {guifg = c.blue}},
    {'typescriptIdentifier', {guifg = c.orange}},
    {'typescriptGlobal', {guifg = c.blue}},
    {'typescriptOperator', {guifg = c.red}},
    {'typescriptNodeGlobal', {guifg = c.blue}},
    {'typescriptExport', {guifg = c.red}},
    {'typescriptImport', {guifg = c.red}},
    {'typescriptTypeParameter', {guifg = c.blue}},
    {'typescriptReadonlyModifier', {guifg = c.red}},
    {'typescriptAccessibilityModifier', {guifg = c.red}},
    {'typescriptAmbientDeclaration', {guifg = c.red}},
    {'typescriptTemplateSubstitution', {guifg = c.purple}},
    {'typescriptTemplateSB', {guifg = c.purple}},
    {'typescriptExceptions', {guifg = c.red}},
    {'typescriptCastKeyword', {guifg = c.red}},
    {'typescriptOptionalMark', {guifg = c.red}},
    {'typescriptNull', {guifg = c.orange}},
    {'typescriptMappedIn', {guifg = c.red}},
    {'typescriptFuncTypeArrow', {guifg = c.red}},
    {'typescriptTernaryOp', {guifg = c.red}},
    {'typescriptParenExp', {guifg = c.fg}},
    {'typescriptIndexExpr', {guifg = c.fg}},
    {'typescriptDotNotation', {guifg = c.grey}},
    {'typescriptGlobalNumberDot', {guifg = c.grey}},
    {'typescriptGlobalStringDot', {guifg = c.grey}},
    {'typescriptGlobalArrayDot', {guifg = c.grey}},
    {'typescriptGlobalObjectDot', {guifg = c.grey}},
    {'typescriptGlobalSymbolDot', {guifg = c.grey}},
    {'typescriptGlobalMathDot', {guifg = c.grey}},
    {'typescriptGlobalDateDot', {guifg = c.grey}},
    {'typescriptGlobalJSONDot', {guifg = c.grey}},
    {'typescriptGlobalRegExpDot', {guifg = c.grey}},
    {'typescriptGlobalPromiseDot', {guifg = c.grey}},
    {'typescriptGlobalURLDot', {guifg = c.grey}},
    {'typescriptGlobalMethod', {guifg = c.green}},
    {'typescriptDOMStorageMethod', {guifg = c.green}},
    {'typescriptFileMethod', {guifg = c.green}},
    {'typescriptFileReaderMethod', {guifg = c.green}},
    {'typescriptFileListMethod', {guifg = c.green}},
    {'typescriptBlobMethod', {guifg = c.green}},
    {'typescriptURLStaticMethod', {guifg = c.green}},
    {'typescriptNumberStaticMethod', {guifg = c.green}},
    {'typescriptNumberMethod', {guifg = c.green}},
    {'typescriptDOMNodeMethod', {guifg = c.green}},
    {'typescriptPaymentMethod', {guifg = c.green}},
    {'typescriptPaymentResponseMethod', {guifg = c.green}},
    {'typescriptHeadersMethod', {guifg = c.green}},
    {'typescriptRequestMethod', {guifg = c.green}},
    {'typescriptResponseMethod', {guifg = c.green}},
    {'typescriptES6SetMethod', {guifg = c.green}},
    {'typescriptReflectMethod', {guifg = c.green}},
    {'typescriptBOMWindowMethod', {guifg = c.green}},
    {'typescriptGeolocationMethod', {guifg = c.green}},
    {'typescriptServiceWorkerMethod', {guifg = c.green}},
    {'typescriptCacheMethod', {guifg = c.green}},
    {'typescriptES6MapMethod', {guifg = c.green}},
    {'typescriptFunctionMethod', {guifg = c.green}},
    {'typescriptRegExpMethod', {guifg = c.green}},
    {'typescriptXHRMethod', {guifg = c.green}},
    {'typescriptBOMNavigatorMethod', {guifg = c.green}},
    {'typescriptServiceWorkerMethod', {guifg = c.green}},
    {'typescriptIntlMethod', {guifg = c.green}},
    {'typescriptDOMEventTargetMethod', {guifg = c.green}},
    {'typescriptDOMEventMethod', {guifg = c.green}},
    {'typescriptDOMDocMethod', {guifg = c.green}},
    {'typescriptStringStaticMethod', {guifg = c.green}},
    {'typescriptStringMethod', {guifg = c.green}},
    {'typescriptSymbolStaticMethod', {guifg = c.green}},
    {'typescriptObjectStaticMethod', {guifg = c.green}},
    {'typescriptObjectMethod', {guifg = c.green}},
    {'typescriptJSONStaticMethod', {guifg = c.green}},
    {'typescriptEncodingMethod', {guifg = c.green}},
    {'typescriptBOMLocationMethod', {guifg = c.green}},
    {'typescriptPromiseStaticMethod', {guifg = c.green}},
    {'typescriptPromiseMethod', {guifg = c.green}},
    {'typescriptSubtleCryptoMethod', {guifg = c.green}},
    {'typescriptCryptoMethod', {guifg = c.green}},
    {'typescriptBOMHistoryMethod', {guifg = c.green}},
    {'typescriptDOMFormMethod', {guifg = c.green}},
    {'typescriptConsoleMethod', {guifg = c.green}},
    {'typescriptDateStaticMethod', {guifg = c.green}},
    {'typescriptDateMethod', {guifg = c.green}},
    {'typescriptArrayStaticMethod', {guifg = c.green}},
    {'typescriptArrayMethod', {guifg = c.green}},
    {'typescriptMathStaticMethod', {guifg = c.green}},
    {'typescriptStringProperty', {guifg = c.fg}},
    {'typescriptDOMStorageProp', {guifg = c.fg}},
    {'typescriptFileReaderProp', {guifg = c.fg}},
    {'typescriptURLUtilsProp', {guifg = c.fg}},
    {'typescriptNumberStaticProp', {guifg = c.fg}},
    {'typescriptDOMNodeProp', {guifg = c.fg}},
    {'typescriptBOMWindowProp', {guifg = c.fg}},
    {'typescriptRequestProp', {guifg = c.fg}},
    {'typescriptResponseProp', {guifg = c.fg}},
    {'typescriptPaymentProp', {guifg = c.fg}},
    {'typescriptPaymentResponseProp', {guifg = c.fg}},
    {'typescriptPaymentAddressProp', {guifg = c.fg}},
    {'typescriptPaymentShippingOptionProp', {guifg = c.fg}},
    {'typescriptES6SetProp', {guifg = c.fg}},
    {'typescriptServiceWorkerProp', {guifg = c.fg}},
    {'typescriptES6MapProp', {guifg = c.fg}},
    {'typescriptRegExpStaticProp', {guifg = c.fg}},
    {'typescriptRegExpProp', {guifg = c.fg}},
    {'typescriptBOMNavigatorProp', {guifg = c.green}},
    {'typescriptXHRProp', {guifg = c.fg}},
    {'typescriptDOMEventProp', {guifg = c.fg}},
    {'typescriptDOMDocProp', {guifg = c.fg}},
    {'typescriptBOMNetworkProp', {guifg = c.fg}},
    {'typescriptSymbolStaticProp', {guifg = c.fg}},
    {'typescriptEncodingProp', {guifg = c.fg}},
    {'typescriptBOMLocationProp', {guifg = c.fg}},
    {'typescriptCryptoProp', {guifg = c.fg}},
    {'typescriptDOMFormProp', {guifg = c.fg}},
    {'typescriptBOMHistoryProp', {guifg = c.fg}},
    {'typescriptMathStaticProp', {guifg = c.fg}},

    ---------- C++ ----------

    {'cLabel', {guifg = c.red}},
    {'cppSTLnamespace', {guifg = c.blue}},
    {'cppSTLtype', {guifg = c.blue}},
    {'cppAccess', {guifg = c.red}},
    {'cppStructure', {guifg = c.red}},
    {'cppSTLios', {guifg = c.blue}},
    {'cppSTLiterator', {guifg = c.blue}},
    {'cppSTLexception', {guifg = c.red}},

    ---------- C# ----------

    {'csUnspecifiedStatement', {guifg = c.red}},
    {'csStorage', {guifg = c.red}},
    {'csClass', {guifg = c.red}},
    {'csNewType', {guifg = c.blue}},
    {'csContextualStatement', {guifg = c.red}},
    {'csInterpolationDelimiter', {guifg = c.purple}},
    {'csInterpolation', {guifg = c.purple}},
    {'csEndColon', {guifg = c.fg}},

    ---------- PYTHON ----------

    {'pythonBuiltin', {guifg = c.blue}},
    {'pythonExceptions', {guifg = c.red}},
    {'pythonDecoratorName', {guifg = c.orange}},
    {'pythonExClass', {guifg = c.blue}},
    {'pythonBuiltinType', {guifg = c.blue}},
    {'pythonBuiltinObj', {guifg = c.orange}},
    {'pythonDottedName', {guifg = c.orange}},
    {'pythonBuiltinFunc', {guifg = c.green}},
    {'pythonFunction', {guifg = c.green}},
    {'pythonDecorator', {guifg = c.orange}},
    {'pythonInclude', {link = 'Include'}},
    {'pythonImport', {link = 'PreProc'}},
    {'pythonOperator', {guifg = c.red}},
    {'pythonConditional', {guifg = c.red}},
    {'pythonRepeat', {guifg = c.red}},
    {'pythonException', {guifg = c.red}},
    {'pythonNone', {guifg = c.orange}},
    {'pythonCoding', {guifg = c.grey}},
    {'pythonDot', {guifg = c.grey}},

    ---------- LUA ----------

    {'luaFunc', {guifg = c.green}},
    {'luaFunction', {guifg = c.red}},
    {'luaTable', {guifg = c.fg}},
    {'luaIn', {guifg = c.red}},
    {'luaFuncCall', {guifg = c.green}},
    {'luaLocal', {guifg = c.red}},
    {'luaSpecialValue', {guifg = c.green}},
    {'luaBraces', {guifg = c.fg}},
    {'luaBuiltIn', {guifg = c.blue}},
    {'luaNoise', {guifg = c.grey}},
    {'luaLabel', {guifg = c.purple}},
    {'luaFuncTable', {guifg = c.blue}},
    {'luaFuncArgName', {guifg = c.fg}},
    {'luaEllipsis', {guifg = c.red}},
    {'luaDocTag', {guifg = c.green}},

    ---------- JAVA ----------

    {'javaClassDecl', {guifg = c.red}},
    {'javaMethodDecl', {guifg = c.red}},
    {'javaVarArg', {guifg = c.fg}},
    {'javaAnnotation', {guifg = c.purple}},
    {'javaUserLabel', {guifg = c.purple}},
    {'javaTypedef', {guifg = c.orange}},
    {'javaParen', {guifg = c.fg}},
    {'javaParen1', {guifg = c.fg}},
    {'javaParen2', {guifg = c.fg}},
    {'javaParen3', {guifg = c.fg}},
    {'javaParen4', {guifg = c.fg}},
    {'javaParen5', {guifg = c.fg}},

    ---------- KOTLIN ----------

    {'ktSimpleInterpolation', {guifg = c.purple}},
    {'ktComplexInterpolation', {guifg = c.purple}},
    {'ktComplexInterpolationBrace', {guifg = c.purple}},
    {'ktStructure', {guifg = c.red}},
    {'ktKeyword', {guifg = c.orange}},

    ---------- RUST ----------

    {'rustStructure', {guifg = c.red}},
    {'rustIdentifier', {guifg = c.orange}},
    {'rustModPath', {guifg = c.blue}},
    {'rustModPathSep', {guifg = c.grey}},
    {'rustSelf', {guifg = c.orange}},
    {'rustSuper', {guifg = c.orange}},
    {'rustDeriveTrait', {guifg = c.purple}},
    {'rustEnumVariant', {guifg = c.purple}},
    {'rustMacroVariable', {guifg = c.orange}},
    {'rustAssert', {guifg = c.green}},
    {'rustPanic', {guifg = c.green}},
    {'rustPubScopeCrate', {guifg = c.blue}},
    {'rustAttribute', {guifg = c.purple}},

    ---------- SWIFT ----------

    {'swiftInterpolatedWrapper', {guifg = c.purple}},
    {'swiftInterpolatedString', {guifg = c.purple}},
    {'swiftProperty', {guifg = c.fg}},
    {'swiftTypeDeclaration', {guifg = c.red}},
    {'swiftClosureArgument', {guifg = c.orange}},
    {'swiftStructure', {guifg = c.red}},

    ---------- ZSH ----------

    {'shRange', {guifg = c.fg}},
    {'shOption', {guifg = c.purple}},
    {'shQuote', {guifg = c.yellow}},
    {'shVariable', {guifg = c.blue}},
    {'shDerefSimple', {guifg = c.blue}},
    {'shDerefVar', {guifg = c.blue}},
    {'shDerefSpecial', {guifg = c.blue}},
    {'shDerefOff', {guifg = c.blue}},
    {'shVarAssign', {guifg = c.red}},
    {'shFunctionOne', {guifg = c.green}},
    {'shFunctionKey', {guifg = c.red}},

    {'zshOption', {guifg = c.blue}},
    {'zshSubst', {guifg = c.orange}},
    {'zshFunction', {guifg = c.green}},

    ---------- VIM ----------

    {'vimnotfunc', {guifg = c.red}},
    {'vimcommand', {guifg = c.red}},
    {'vimCommentTitle', {guifg = c.grey, guibg = 'NONE', gui = 'bold'}},
    {'vimLet', {guifg = c.red}},
    {'vimFunction', {guifg = c.green}},
    {'vimIsCommand', {guifg = c.fg}},
    {'vimUserFunc', {guifg = c.green}},
    {'vimFuncName', {guifg = c.green}},
    {'vimMap', {guifg = c.blue}},
    {'vimNotation', {guifg = c.purple}},
    {'vimMapLhs', {guifg = c.green}},
    {'vimMapRhs', {guifg = c.green}},
    {'vimSetEqual', {guifg = c.blue}},
    {'vimSetSep', {guifg = c.fg}},
    {'vimOption', {guifg = c.blue}},
    {'vimUserAttrbKey', {guifg = c.blue}},
    {'vimUserAttrb', {guifg = c.green}},
    {'vimAutoCmdSfxList', {guifg = c.orange}},
    {'vimSynType', {guifg = c.orange}},
    {'vimHiBang', {guifg = c.orange}},
    {'vimSet', {guifg = c.blue}},
    {'vimSetSep', {guifg = c.grey}},

    ---------- MAKE ----------

    {'makeIdent', {guifg = c.purple}},
    {'makeSpecTarget', {guifg = c.blue}},
    {'makeTarget', {guifg = c.orange}},
    {'makeCommands', {guifg = c.red}},

    ---------- MARKDOWN ----------

    {'markdownH1', {guifg = c.red, guibg = 'NONE', gui = 'bold'}},
    {'markdownH2', {guifg = c.orange, guibg = 'NONE', gui = 'bold'}},
    {'markdownH3', {guifg = c.yellow, guibg = 'NONE', gui = 'bold'}},
    {'markdownH4', {guifg = c.green, guibg = 'NONE', gui = 'bold'}},
    {'markdownH5', {guifg = c.blue, guibg = 'NONE', gui = 'bold'}},
    {'markdownH6', {guifg = c.purple, guibg = 'NONE', gui = 'bold'}},
    {'markdownUrl', {guifg = c.blue, guibg = 'NONE', gui = 'underline'}},
    {'markdownItalic', {guifg = 'NONE', guibg = 'NONE', gui = 'italic'}},
    {'markdownBold', {guifg = 'NONE', guibg = 'NONE', gui = 'bold'}},
    {'markdownItalicDelimiter', {guifg = c.grey, guibg = 'NONE', gui = 'italic'}},
    {'markdownCode', {guifg = c.green}},
    {'markdownCodeBlock', {guifg = c.green}},
    {'markdownCodeDelimiter', {guifg = c.green}},
    {'markdownBlockquote', {guifg = c.grey}},
    {'markdownListMarker', {guifg = c.red}},
    {'markdownOrderedListMarker', {guifg = c.red}},
    {'markdownRule', {guifg = c.purple}},
    {'markdownHeadingRule', {guifg = c.grey}},
    {'markdownUrlDelimiter', {guifg = c.grey}},
    {'markdownLinkDelimiter', {guifg = c.grey}},
    {'markdownLinkTextDelimiter', {guifg = c.grey}},
    {'markdownHeadingDelimiter', {guifg = c.grey}},
    {'markdownLinkText', {guifg = c.red}},
    {'markdownUrlTitleDelimiter', {guifg = c.green}},
    {'markdownIdDeclaration', {link = 'markdownLinkText'}},
    {'markdownBoldDelimiter', {guifg = c.grey}},
    {'markdownId', {guifg = c.yellow}},
    {'mkdURL', {guifg = c.blue, guibg = 'NONE', gui = 'underline'}},
    {'mkdInlineURL', {guifg = c.blue, guibg = 'NONE', gui = 'underline'}},
    {'mkdItalic', {guifg = c.grey, guibg = 'NONE', gui = 'italic'}},
    {'mkdCodeDelimiter', {guifg = c.green}},
    {'mkdBold', {guifg = c.grey}},
    {'mkdLink', {guifg = c.red}},
    {'mkdHeading', {guifg = c.grey}},
    {'mkdListItem', {guifg = c.red}},
    {'mkdRule', {guifg = c.purple}},
    {'mkdDelimiter', {guifg = c.grey}},
    {'mkdId', {guifg = c.yellow}},

    ---------- JSON ----------

    {'jsonKeyword', {guifg = c.red}},
    {'jsonString', {guifg = c.green}},
    {'jsonBoolean', {guifg = c.blue}},
    {'jsonNoise', {guifg = c.grey}},
    {'jsonQuote', {guifg = c.grey}},
    {'jsonBraces', {guifg = c.fg}},

    ---------- GIT ----------

    {'diffAdded', {guifg = c.green}},
    {'diffRemoved', {guifg = c.red}},
    {'diffChanged', {guifg = c.blue}},
    {'diffOldFile', {guifg = c.yellow}},
    {'diffNewFile', {guifg = c.orange}},
    {'diffFile', {guifg = c.purple}},
    {'diffLine', {guifg = c.grey}},
    {'diffIndexLine', {guifg = c.purple}},

    {'gitcommitSummary', {guifg = c.red}},
    {'gitcommitUntracked', {guifg = c.grey}},
    {'gitcommitDiscarded', {guifg = c.grey}},
    {'gitcommitSelected', {guifg = c.grey}},
    {'gitcommitUnmerged', {guifg = c.grey}},
    {'gitcommitOnBranch', {guifg = c.grey}},
    {'gitcommitArrow', {guifg = c.grey}},
    {'gitcommitFile', {guifg = c.green}},

    ---------- HELP ----------

    {'helpNote', {guifg = c.purple, guibg = 'NONE', gui = 'bold'}},
    {'helpHeadline', {guifg = c.red, guibg = 'NONE', gui = 'bold'}},
    {'helpHeader', {guifg = c.orange, guibg = 'NONE', gui = 'bold'}},
    {'helpURL', {guifg = c.green, guibg = 'NONE', gui = 'underline'}},
    {'helpHyperTextEntry', {guifg = c.blue, guibg = 'NONE', gui = 'bold'}},
    {'helpHyperTextJump', {guifg = c.blue}},
    {'helpCommand', {guifg = c.yellow}},
    {'helpExample', {guifg = c.green}},
    {'helpSpecial', {guifg = c.purple}},
    {'helpSectionDelim', {guifg = c.grey}},

    ---------- STARTSCREEN ----------

    {'DashboardHeader', {guifg = c.red, guibg = 'NONE'}},
    {'DashboardCenter', {guifg = c.blue, guibg = 'NONE'}},

    {'StartifyBracket', {guifg = c.grey}},
    {'StartifyFile', {guifg = c.green}},
    {'StartifyNumber', {guifg = c.orange}},
    {'StartifyPath', {guifg = c.grey}},
    {'StartifySlash', {guifg = c.grey}},
    {'StartifySection', {guifg = c.blue}},
    {'StartifyHeader', {guifg = c.red}},
    {'StartifySpecial', {guifg = c.grey}},

    ---------- GIT CONFLICT ----------

    {'ConflictMarkerBegin', {guifg = c.red, guibg = 'NONE'}},
    {'ConflictMarkerSeparator', {guifg = c.red, guibg = 'NONE'}},
    {'ConflictMarkerOurs', {guifg = 'NONE', guibg = c.diff_green}},
    {'ConflictMarkerTheirs', {guifg = 'NONE', guibg = c.diff_blue}},
    {'ConflictMarkerEnd', {guifg = c.red, guibg = 'NONE'}},

    ---------- NVIM TREE ----------

    {'NvimTreeFolderName', {guifg = c.blue}},
    {'NvimTreeOpenedFolderName', {link = 'NvimTreeFolderName'}},
    {'NvimTreeEmptyFolderName', {link = 'NvimTreeFolderName'}},
}
