lua << EOF

local gitmoji = function(text, emoji)
    vim.cmd([[silent! execute('%s/]] .. string.format([[%s/%s/gI')]], text, emoji))
end

gitmoji(':sparkles:', '✨')
gitmoji(':art:', '🎨')
gitmoji(':zap:', '⚡️')
gitmoji(':fire:', '🔥')
gitmoji(':bug:', '🐛')
gitmoji(':ambulance:', '🚑️')
gitmoji(':sparkles:', '✨')
gitmoji(':memo:', '📝')
gitmoji(':rocket:', '🚀')
gitmoji(':lipstick:', '💄')
gitmoji(':tada:', '🎉')
gitmoji(':white_check_mark:', '✅')
gitmoji(':lock:', '🔒️')
gitmoji(':bookmark:', '🔖')
gitmoji(':rotating_light:', '🚨')
gitmoji(':construction:', '🚧')
gitmoji(':green_heart:', '💚')
gitmoji(':arrow_down:', '⬇️')
gitmoji(':arrow_up:', '⬆️')
gitmoji(':pushpin:', '📌')
gitmoji(':construction_worker:', '👷')
gitmoji(':chart_with_upwards_trend:', '📈')
gitmoji(':recycle:', '♻️')
gitmoji(':heavy_plus_sign:', '➕')
gitmoji(':heavy_minus_sign:', '➖')
gitmoji(':wrench:', '🔧')
gitmoji(':hammer:', '🔨')
gitmoji(':globe_with_meridians:', '🌐')
gitmoji(':pencil2:', '✏️')
gitmoji(':poop:', '💩')
gitmoji(':rewind:', '⏪️')
gitmoji(':twisted_rightwards_arrows:', '🔀')
gitmoji(':package:', '📦️')
gitmoji(':alien:', '👽️')
gitmoji(':truck:', '🚚')
gitmoji(':page_facing_up:', '📄')
gitmoji(':boom:', '💥')
gitmoji(':bento:', '🍱')
gitmoji(':wheelchair:', '♿️')
gitmoji(':bulb:', '💡')
gitmoji(':beers:', '🍻')
gitmoji(':speech_balloon:', '💬')
gitmoji(':card_file_box:', '🗃️')
gitmoji(':loud_sound:', '🔊')
gitmoji(':mute:', '🔇')
gitmoji(':busts_in_silhouette:', '👥')
gitmoji(':children_crossing:', '🚸')
gitmoji(':building_construction:', '🏗️')
gitmoji(':iphone:', '📱')
gitmoji(':clown_face:', '🤡')
gitmoji(':egg:', '🥚')
gitmoji(':see_no_evil:', '🙈')
gitmoji(':camera_flash:', '📸')
gitmoji(':alembic:', '⚗️')
gitmoji(':mag:', '🔍️')
gitmoji(':label:', '🏷️')
gitmoji(':seedling:', '🌱')
gitmoji(':triangular_flag_on_post:', '🚩')
gitmoji(':goal_net:', '🥅')
gitmoji(':dizzy:', '💫')
gitmoji(':wastebasket:', '🗑️')
gitmoji(':passport_control:', '🛂')
gitmoji(':adhesive_bandage:', '🩹')
gitmoji(':monocle_face:', '🧐')
gitmoji(':coffin:', '⚰️')

EOF
