#!/bin/sh

NVIM=/usr/local/bin/nvim
ARGS_ONCE="$@"

export SESSION_FILE=$(mktemp)

# Injected config
CFG_FILE=$(mktemp)
cat > $CFG_FILE <<EOF
lua << END
vim.api.nvim_create_user_command('R', function()
    vim.api.nvim_command('silent! mksession! ' .. vim.env.SESSION_FILE)
    vim.api.nvim_command('silent! qall')
  end, {})
END
EOF

function cleanup {
   rm -f $CFG_FILE
   rm -f $SESSION_FILE
}
trap cleanup EXIT

# TODO: Can I get this to work on both linux and mac?
# Stat command is different between those two
function get_mtime {
   stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" $1
}

while true; do
   ORIG_MTIME=$(get_mtime $SESSION_FILE)
   $NVIM -S $CFG_FILE -S $SESSION_FILE $ARGS_ONCE
   ARGS_ONCE=""

   if [ $? -ne 0 ]; then
      echo "Vim crashed! Press a key to re-enter... (Ctrl-C to abort)"
      read ans
      continue
   fi

   NEW_MTIME=$(get_mtime $SESSION_FILE)
   if [ "$ORIG_MTIME" = "$NEW_MTIME" ]; then
      break
   fi

done
